package com.apexsoft.ysprj.clerk.user.domain;

import java.util.Date;

public class Clerk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.USER_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.NAME
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.MOBI_NUM
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String mobiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.TEMP_PSWD_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String tempPswdYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.MAIL_ADDR
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String mailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.SMS_RECV_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String smsRecvYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.MAIL_RECV_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String mailRecvYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.USER_UNIV_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String userUnivCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.COLL_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String collCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.DEPT_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.USER_AGRE_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String userAgreYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.PRIV_INFO_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String privInfoYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.USER_STS_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String userStsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.ENABLED
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.CRE_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.CRE_DATE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.MOD_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.MOD_DATE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private Date modDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_UNIV.PSWD
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    private byte[] pswd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.USER_ID
     *
     * @return the value of USER_UNIV.USER_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.USER_ID
     *
     * @param userId the value for USER_UNIV.USER_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.NAME
     *
     * @return the value of USER_UNIV.NAME
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.NAME
     *
     * @param name the value for USER_UNIV.NAME
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.MOBI_NUM
     *
     * @return the value of USER_UNIV.MOBI_NUM
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getMobiNum() {
        return mobiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.MOBI_NUM
     *
     * @param mobiNum the value for USER_UNIV.MOBI_NUM
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setMobiNum(String mobiNum) {
        this.mobiNum = mobiNum == null ? null : mobiNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.TEMP_PSWD_YN
     *
     * @return the value of USER_UNIV.TEMP_PSWD_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getTempPswdYn() {
        return tempPswdYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.TEMP_PSWD_YN
     *
     * @param tempPswdYn the value for USER_UNIV.TEMP_PSWD_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setTempPswdYn(String tempPswdYn) {
        this.tempPswdYn = tempPswdYn == null ? null : tempPswdYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.MAIL_ADDR
     *
     * @return the value of USER_UNIV.MAIL_ADDR
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getMailAddr() {
        return mailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.MAIL_ADDR
     *
     * @param mailAddr the value for USER_UNIV.MAIL_ADDR
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setMailAddr(String mailAddr) {
        this.mailAddr = mailAddr == null ? null : mailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.SMS_RECV_YN
     *
     * @return the value of USER_UNIV.SMS_RECV_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getSmsRecvYn() {
        return smsRecvYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.SMS_RECV_YN
     *
     * @param smsRecvYn the value for USER_UNIV.SMS_RECV_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setSmsRecvYn(String smsRecvYn) {
        this.smsRecvYn = smsRecvYn == null ? null : smsRecvYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.MAIL_RECV_YN
     *
     * @return the value of USER_UNIV.MAIL_RECV_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getMailRecvYn() {
        return mailRecvYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.MAIL_RECV_YN
     *
     * @param mailRecvYn the value for USER_UNIV.MAIL_RECV_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setMailRecvYn(String mailRecvYn) {
        this.mailRecvYn = mailRecvYn == null ? null : mailRecvYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.USER_UNIV_CODE
     *
     * @return the value of USER_UNIV.USER_UNIV_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getUserUnivCode() {
        return userUnivCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.USER_UNIV_CODE
     *
     * @param userUnivCode the value for USER_UNIV.USER_UNIV_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setUserUnivCode(String userUnivCode) {
        this.userUnivCode = userUnivCode == null ? null : userUnivCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.COLL_CODE
     *
     * @return the value of USER_UNIV.COLL_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getCollCode() {
        return collCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.COLL_CODE
     *
     * @param collCode the value for USER_UNIV.COLL_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setCollCode(String collCode) {
        this.collCode = collCode == null ? null : collCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.DEPT_CODE
     *
     * @return the value of USER_UNIV.DEPT_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.DEPT_CODE
     *
     * @param deptCode the value for USER_UNIV.DEPT_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.USER_AGRE_YN
     *
     * @return the value of USER_UNIV.USER_AGRE_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getUserAgreYn() {
        return userAgreYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.USER_AGRE_YN
     *
     * @param userAgreYn the value for USER_UNIV.USER_AGRE_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setUserAgreYn(String userAgreYn) {
        this.userAgreYn = userAgreYn == null ? null : userAgreYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.PRIV_INFO_YN
     *
     * @return the value of USER_UNIV.PRIV_INFO_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getPrivInfoYn() {
        return privInfoYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.PRIV_INFO_YN
     *
     * @param privInfoYn the value for USER_UNIV.PRIV_INFO_YN
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setPrivInfoYn(String privInfoYn) {
        this.privInfoYn = privInfoYn == null ? null : privInfoYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.USER_STS_CODE
     *
     * @return the value of USER_UNIV.USER_STS_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getUserStsCode() {
        return userStsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.USER_STS_CODE
     *
     * @param userStsCode the value for USER_UNIV.USER_STS_CODE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setUserStsCode(String userStsCode) {
        this.userStsCode = userStsCode == null ? null : userStsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.ENABLED
     *
     * @return the value of USER_UNIV.ENABLED
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.ENABLED
     *
     * @param enabled the value for USER_UNIV.ENABLED
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.CRE_ID
     *
     * @return the value of USER_UNIV.CRE_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.CRE_ID
     *
     * @param creId the value for USER_UNIV.CRE_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.CRE_DATE
     *
     * @return the value of USER_UNIV.CRE_DATE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.CRE_DATE
     *
     * @param creDate the value for USER_UNIV.CRE_DATE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.MOD_ID
     *
     * @return the value of USER_UNIV.MOD_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.MOD_ID
     *
     * @param modId the value for USER_UNIV.MOD_ID
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.MOD_DATE
     *
     * @return the value of USER_UNIV.MOD_DATE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.MOD_DATE
     *
     * @param modDate the value for USER_UNIV.MOD_DATE
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_UNIV.PSWD
     *
     * @return the value of USER_UNIV.PSWD
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public byte[] getPswd() {
        return pswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_UNIV.PSWD
     *
     * @param pswd the value for USER_UNIV.PSWD
     *
     * @mbggenerated Mon Aug 25 20:42:56 KST 2014
     */
    public void setPswd(byte[] pswd) {
        this.pswd = pswd;
    }
}