package com.apexsoft.ysprj.applicants.payment.domain;

import java.util.Date;

public class ApplicationPaymentCurStat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.APPL_NO
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private Integer applNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.ADMS_FEE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private Integer admsFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.PAY_AMT
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private Integer payAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.PAY_TYPE_CODE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String payTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.PAY_STS_CODE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String payStsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.PAY_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.RTN_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String rtnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.LGD_OID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String lgdOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.LGD_TID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String lgdTid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.CRE_ID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.CRE_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.MOD_ID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_PAY_CS.MOD_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.APPL_NO
     *
     * @return the value of APPL_PAY_CS.APPL_NO
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public Integer getApplNo() {
        return applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.APPL_NO
     *
     * @param applNo the value for APPL_PAY_CS.APPL_NO
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setApplNo(Integer applNo) {
        this.applNo = applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.ADMS_FEE
     *
     * @return the value of APPL_PAY_CS.ADMS_FEE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public Integer getAdmsFee() {
        return admsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.ADMS_FEE
     *
     * @param admsFee the value for APPL_PAY_CS.ADMS_FEE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setAdmsFee(Integer admsFee) {
        this.admsFee = admsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.PAY_AMT
     *
     * @return the value of APPL_PAY_CS.PAY_AMT
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public Integer getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.PAY_AMT
     *
     * @param payAmt the value for APPL_PAY_CS.PAY_AMT
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setPayAmt(Integer payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.PAY_TYPE_CODE
     *
     * @return the value of APPL_PAY_CS.PAY_TYPE_CODE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getPayTypeCode() {
        return payTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.PAY_TYPE_CODE
     *
     * @param payTypeCode the value for APPL_PAY_CS.PAY_TYPE_CODE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setPayTypeCode(String payTypeCode) {
        this.payTypeCode = payTypeCode == null ? null : payTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.PAY_STS_CODE
     *
     * @return the value of APPL_PAY_CS.PAY_STS_CODE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getPayStsCode() {
        return payStsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.PAY_STS_CODE
     *
     * @param payStsCode the value for APPL_PAY_CS.PAY_STS_CODE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setPayStsCode(String payStsCode) {
        this.payStsCode = payStsCode == null ? null : payStsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.PAY_DATE
     *
     * @return the value of APPL_PAY_CS.PAY_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.PAY_DATE
     *
     * @param payDate the value for APPL_PAY_CS.PAY_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate == null ? null : payDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.RTN_DATE
     *
     * @return the value of APPL_PAY_CS.RTN_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getRtnDate() {
        return rtnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.RTN_DATE
     *
     * @param rtnDate the value for APPL_PAY_CS.RTN_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setRtnDate(String rtnDate) {
        this.rtnDate = rtnDate == null ? null : rtnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.LGD_OID
     *
     * @return the value of APPL_PAY_CS.LGD_OID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getLgdOid() {
        return lgdOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.LGD_OID
     *
     * @param lgdOid the value for APPL_PAY_CS.LGD_OID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setLgdOid(String lgdOid) {
        this.lgdOid = lgdOid == null ? null : lgdOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.LGD_TID
     *
     * @return the value of APPL_PAY_CS.LGD_TID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getLgdTid() {
        return lgdTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.LGD_TID
     *
     * @param lgdTid the value for APPL_PAY_CS.LGD_TID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setLgdTid(String lgdTid) {
        this.lgdTid = lgdTid == null ? null : lgdTid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.CRE_ID
     *
     * @return the value of APPL_PAY_CS.CRE_ID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.CRE_ID
     *
     * @param creId the value for APPL_PAY_CS.CRE_ID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.CRE_DATE
     *
     * @return the value of APPL_PAY_CS.CRE_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.CRE_DATE
     *
     * @param creDate the value for APPL_PAY_CS.CRE_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.MOD_ID
     *
     * @return the value of APPL_PAY_CS.MOD_ID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.MOD_ID
     *
     * @param modId the value for APPL_PAY_CS.MOD_ID
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_PAY_CS.MOD_DATE
     *
     * @return the value of APPL_PAY_CS.MOD_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_PAY_CS.MOD_DATE
     *
     * @param modDate the value for APPL_PAY_CS.MOD_DATE
     *
     * @mbggenerated Mon Feb 16 17:33:53 KST 2015
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}