package com.apexsoft.ysprj.applicants.payment.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XPayCancelRequestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public XPayCancelRequestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLgdTxnameIsNull() {
            addCriterion("LGD_TXNAME is null");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameIsNotNull() {
            addCriterion("LGD_TXNAME is not null");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameEqualTo(String value) {
            addCriterion("LGD_TXNAME =", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameNotEqualTo(String value) {
            addCriterion("LGD_TXNAME <>", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameGreaterThan(String value) {
            addCriterion("LGD_TXNAME >", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameGreaterThanOrEqualTo(String value) {
            addCriterion("LGD_TXNAME >=", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameLessThan(String value) {
            addCriterion("LGD_TXNAME <", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameLessThanOrEqualTo(String value) {
            addCriterion("LGD_TXNAME <=", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameLike(String value) {
            addCriterion("LGD_TXNAME like", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameNotLike(String value) {
            addCriterion("LGD_TXNAME not like", value, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameIn(List<String> values) {
            addCriterion("LGD_TXNAME in", values, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameNotIn(List<String> values) {
            addCriterion("LGD_TXNAME not in", values, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameBetween(String value1, String value2) {
            addCriterion("LGD_TXNAME between", value1, value2, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdTxnameNotBetween(String value1, String value2) {
            addCriterion("LGD_TXNAME not between", value1, value2, "lgdTxname");
            return (Criteria) this;
        }

        public Criteria andLgdMidIsNull() {
            addCriterion("LGD_MID is null");
            return (Criteria) this;
        }

        public Criteria andLgdMidIsNotNull() {
            addCriterion("LGD_MID is not null");
            return (Criteria) this;
        }

        public Criteria andLgdMidEqualTo(String value) {
            addCriterion("LGD_MID =", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidNotEqualTo(String value) {
            addCriterion("LGD_MID <>", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidGreaterThan(String value) {
            addCriterion("LGD_MID >", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidGreaterThanOrEqualTo(String value) {
            addCriterion("LGD_MID >=", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidLessThan(String value) {
            addCriterion("LGD_MID <", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidLessThanOrEqualTo(String value) {
            addCriterion("LGD_MID <=", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidLike(String value) {
            addCriterion("LGD_MID like", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidNotLike(String value) {
            addCriterion("LGD_MID not like", value, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidIn(List<String> values) {
            addCriterion("LGD_MID in", values, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidNotIn(List<String> values) {
            addCriterion("LGD_MID not in", values, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidBetween(String value1, String value2) {
            addCriterion("LGD_MID between", value1, value2, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdMidNotBetween(String value1, String value2) {
            addCriterion("LGD_MID not between", value1, value2, "lgdMid");
            return (Criteria) this;
        }

        public Criteria andLgdTidIsNull() {
            addCriterion("LGD_TID is null");
            return (Criteria) this;
        }

        public Criteria andLgdTidIsNotNull() {
            addCriterion("LGD_TID is not null");
            return (Criteria) this;
        }

        public Criteria andLgdTidEqualTo(String value) {
            addCriterion("LGD_TID =", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidNotEqualTo(String value) {
            addCriterion("LGD_TID <>", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidGreaterThan(String value) {
            addCriterion("LGD_TID >", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidGreaterThanOrEqualTo(String value) {
            addCriterion("LGD_TID >=", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidLessThan(String value) {
            addCriterion("LGD_TID <", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidLessThanOrEqualTo(String value) {
            addCriterion("LGD_TID <=", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidLike(String value) {
            addCriterion("LGD_TID like", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidNotLike(String value) {
            addCriterion("LGD_TID not like", value, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidIn(List<String> values) {
            addCriterion("LGD_TID in", values, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidNotIn(List<String> values) {
            addCriterion("LGD_TID not in", values, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidBetween(String value1, String value2) {
            addCriterion("LGD_TID between", value1, value2, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andLgdTidNotBetween(String value1, String value2) {
            addCriterion("LGD_TID not between", value1, value2, "lgdTid");
            return (Criteria) this;
        }

        public Criteria andCreDateIsNull() {
            addCriterion("CRE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreDateIsNotNull() {
            addCriterion("CRE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreDateEqualTo(Date value) {
            addCriterion("CRE_DATE =", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotEqualTo(Date value) {
            addCriterion("CRE_DATE <>", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateGreaterThan(Date value) {
            addCriterion("CRE_DATE >", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CRE_DATE >=", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateLessThan(Date value) {
            addCriterion("CRE_DATE <", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateLessThanOrEqualTo(Date value) {
            addCriterion("CRE_DATE <=", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateIn(List<Date> values) {
            addCriterion("CRE_DATE in", values, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotIn(List<Date> values) {
            addCriterion("CRE_DATE not in", values, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateBetween(Date value1, Date value2) {
            addCriterion("CRE_DATE between", value1, value2, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotBetween(Date value1, Date value2) {
            addCriterion("CRE_DATE not between", value1, value2, "creDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 14 14:56:38 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XPAY_CANC_REQ
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}