package com.apexsoft.ysprj.applicants.payment.domain;

import java.util.Date;

public class XPayCertResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CERT_RSLT.LGD_RESPCODE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdRespcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CERT_RSLT.LGD_RESPMSG
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdRespmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CERT_RSLT.LGD_MID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdMid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CERT_RSLT.LGD_OID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CERT_RSLT.LGD_AMOUNT
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CERT_RSLT.LGD_PAYKEY
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdPaykey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CERT_RSLT.CRE_DATE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private Date creDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CERT_RSLT.LGD_RESPCODE
     *
     * @return the value of XPAY_CERT_RSLT.LGD_RESPCODE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdRespcode() {
        return lgdRespcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CERT_RSLT.LGD_RESPCODE
     *
     * @param lgdRespcode the value for XPAY_CERT_RSLT.LGD_RESPCODE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdRespcode(String lgdRespcode) {
        this.lgdRespcode = lgdRespcode == null ? null : lgdRespcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CERT_RSLT.LGD_RESPMSG
     *
     * @return the value of XPAY_CERT_RSLT.LGD_RESPMSG
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdRespmsg() {
        return lgdRespmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CERT_RSLT.LGD_RESPMSG
     *
     * @param lgdRespmsg the value for XPAY_CERT_RSLT.LGD_RESPMSG
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdRespmsg(String lgdRespmsg) {
        this.lgdRespmsg = lgdRespmsg == null ? null : lgdRespmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CERT_RSLT.LGD_MID
     *
     * @return the value of XPAY_CERT_RSLT.LGD_MID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdMid() {
        return lgdMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CERT_RSLT.LGD_MID
     *
     * @param lgdMid the value for XPAY_CERT_RSLT.LGD_MID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdMid(String lgdMid) {
        this.lgdMid = lgdMid == null ? null : lgdMid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CERT_RSLT.LGD_OID
     *
     * @return the value of XPAY_CERT_RSLT.LGD_OID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdOid() {
        return lgdOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CERT_RSLT.LGD_OID
     *
     * @param lgdOid the value for XPAY_CERT_RSLT.LGD_OID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdOid(String lgdOid) {
        this.lgdOid = lgdOid == null ? null : lgdOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CERT_RSLT.LGD_AMOUNT
     *
     * @return the value of XPAY_CERT_RSLT.LGD_AMOUNT
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdAmount() {
        return lgdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CERT_RSLT.LGD_AMOUNT
     *
     * @param lgdAmount the value for XPAY_CERT_RSLT.LGD_AMOUNT
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdAmount(String lgdAmount) {
        this.lgdAmount = lgdAmount == null ? null : lgdAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CERT_RSLT.LGD_PAYKEY
     *
     * @return the value of XPAY_CERT_RSLT.LGD_PAYKEY
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdPaykey() {
        return lgdPaykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CERT_RSLT.LGD_PAYKEY
     *
     * @param lgdPaykey the value for XPAY_CERT_RSLT.LGD_PAYKEY
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdPaykey(String lgdPaykey) {
        this.lgdPaykey = lgdPaykey == null ? null : lgdPaykey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CERT_RSLT.CRE_DATE
     *
     * @return the value of XPAY_CERT_RSLT.CRE_DATE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CERT_RSLT.CRE_DATE
     *
     * @param creDate the value for XPAY_CERT_RSLT.CRE_DATE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }
}