package com.apexsoft.ysprj.applicants.payment.domain;

import java.util.Date;

public class XPayCancelRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CANC_REQ.LGD_TXNAME
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdTxname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CANC_REQ.LGD_MID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdMid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CANC_REQ.LGD_TID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private String lgdTid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XPAY_CANC_REQ.CRE_DATE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    private Date creDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CANC_REQ.LGD_TXNAME
     *
     * @return the value of XPAY_CANC_REQ.LGD_TXNAME
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdTxname() {
        return lgdTxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CANC_REQ.LGD_TXNAME
     *
     * @param lgdTxname the value for XPAY_CANC_REQ.LGD_TXNAME
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdTxname(String lgdTxname) {
        this.lgdTxname = lgdTxname == null ? null : lgdTxname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CANC_REQ.LGD_MID
     *
     * @return the value of XPAY_CANC_REQ.LGD_MID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdMid() {
        return lgdMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CANC_REQ.LGD_MID
     *
     * @param lgdMid the value for XPAY_CANC_REQ.LGD_MID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdMid(String lgdMid) {
        this.lgdMid = lgdMid == null ? null : lgdMid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CANC_REQ.LGD_TID
     *
     * @return the value of XPAY_CANC_REQ.LGD_TID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public String getLgdTid() {
        return lgdTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CANC_REQ.LGD_TID
     *
     * @param lgdTid the value for XPAY_CANC_REQ.LGD_TID
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setLgdTid(String lgdTid) {
        this.lgdTid = lgdTid == null ? null : lgdTid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XPAY_CANC_REQ.CRE_DATE
     *
     * @return the value of XPAY_CANC_REQ.CRE_DATE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XPAY_CANC_REQ.CRE_DATE
     *
     * @param creDate the value for XPAY_CANC_REQ.CRE_DATE
     *
     * @mbggenerated Sun Sep 14 14:56:38 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }
}