package com.apexsoft.ysprj.applicants.application.domain;

public class ApplicationAcademyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_ACAD.APPL_NO
     *
     * @mbggenerated Fri Sep 12 19:50:54 KST 2014
     */
    private Integer applNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_ACAD.ACAD_SEQ
     *
     * @mbggenerated Fri Sep 12 19:50:54 KST 2014
     */
    private Integer acadSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_ACAD.APPL_NO
     *
     * @return the value of APPL_ACAD.APPL_NO
     *
     * @mbggenerated Fri Sep 12 19:50:54 KST 2014
     */
    public Integer getApplNo() {
        return applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_ACAD.APPL_NO
     *
     * @param applNo the value for APPL_ACAD.APPL_NO
     *
     * @mbggenerated Fri Sep 12 19:50:54 KST 2014
     */
    public void setApplNo(Integer applNo) {
        this.applNo = applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_ACAD.ACAD_SEQ
     *
     * @return the value of APPL_ACAD.ACAD_SEQ
     *
     * @mbggenerated Fri Sep 12 19:50:54 KST 2014
     */
    public Integer getAcadSeq() {
        return acadSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_ACAD.ACAD_SEQ
     *
     * @param acadSeq the value for APPL_ACAD.ACAD_SEQ
     *
     * @mbggenerated Fri Sep 12 19:50:54 KST 2014
     */
    public void setAcadSeq(Integer acadSeq) {
        this.acadSeq = acadSeq;
    }
}