package com.apexsoft.ysprj.applicants.application.domain;

import java.util.Date;

public class ApplicationChangeCancel extends ApplicationChangeCancelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.BEF_DEPT_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String befDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.BEF_ARI_INST_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String befAriInstCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.BEF_CORS_TYPE_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String befCorsTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.BEF_DETL_MAJ_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String befDetlMajCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.BEF_ADMS_FEE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private Integer befAdmsFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.PAY_STS
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String paySts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.CNCL_RESN
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String cnclResn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.CRE_ID
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.CRE_DATE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.MOD_ID
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG_CNCL.MOD_DATE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.BEF_DEPT_CODE
     *
     * @return the value of APPL_CHG_CNCL.BEF_DEPT_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getBefDeptCode() {
        return befDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.BEF_DEPT_CODE
     *
     * @param befDeptCode the value for APPL_CHG_CNCL.BEF_DEPT_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setBefDeptCode(String befDeptCode) {
        this.befDeptCode = befDeptCode == null ? null : befDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.BEF_ARI_INST_CODE
     *
     * @return the value of APPL_CHG_CNCL.BEF_ARI_INST_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getBefAriInstCode() {
        return befAriInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.BEF_ARI_INST_CODE
     *
     * @param befAriInstCode the value for APPL_CHG_CNCL.BEF_ARI_INST_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setBefAriInstCode(String befAriInstCode) {
        this.befAriInstCode = befAriInstCode == null ? null : befAriInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.BEF_CORS_TYPE_CODE
     *
     * @return the value of APPL_CHG_CNCL.BEF_CORS_TYPE_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getBefCorsTypeCode() {
        return befCorsTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.BEF_CORS_TYPE_CODE
     *
     * @param befCorsTypeCode the value for APPL_CHG_CNCL.BEF_CORS_TYPE_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setBefCorsTypeCode(String befCorsTypeCode) {
        this.befCorsTypeCode = befCorsTypeCode == null ? null : befCorsTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.BEF_DETL_MAJ_CODE
     *
     * @return the value of APPL_CHG_CNCL.BEF_DETL_MAJ_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getBefDetlMajCode() {
        return befDetlMajCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.BEF_DETL_MAJ_CODE
     *
     * @param befDetlMajCode the value for APPL_CHG_CNCL.BEF_DETL_MAJ_CODE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setBefDetlMajCode(String befDetlMajCode) {
        this.befDetlMajCode = befDetlMajCode == null ? null : befDetlMajCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.BEF_ADMS_FEE
     *
     * @return the value of APPL_CHG_CNCL.BEF_ADMS_FEE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public Integer getBefAdmsFee() {
        return befAdmsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.BEF_ADMS_FEE
     *
     * @param befAdmsFee the value for APPL_CHG_CNCL.BEF_ADMS_FEE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setBefAdmsFee(Integer befAdmsFee) {
        this.befAdmsFee = befAdmsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.PAY_STS
     *
     * @return the value of APPL_CHG_CNCL.PAY_STS
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getPaySts() {
        return paySts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.PAY_STS
     *
     * @param paySts the value for APPL_CHG_CNCL.PAY_STS
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setPaySts(String paySts) {
        this.paySts = paySts == null ? null : paySts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.CNCL_RESN
     *
     * @return the value of APPL_CHG_CNCL.CNCL_RESN
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getCnclResn() {
        return cnclResn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.CNCL_RESN
     *
     * @param cnclResn the value for APPL_CHG_CNCL.CNCL_RESN
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setCnclResn(String cnclResn) {
        this.cnclResn = cnclResn == null ? null : cnclResn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.CRE_ID
     *
     * @return the value of APPL_CHG_CNCL.CRE_ID
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.CRE_ID
     *
     * @param creId the value for APPL_CHG_CNCL.CRE_ID
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.CRE_DATE
     *
     * @return the value of APPL_CHG_CNCL.CRE_DATE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.CRE_DATE
     *
     * @param creDate the value for APPL_CHG_CNCL.CRE_DATE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.MOD_ID
     *
     * @return the value of APPL_CHG_CNCL.MOD_ID
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.MOD_ID
     *
     * @param modId the value for APPL_CHG_CNCL.MOD_ID
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG_CNCL.MOD_DATE
     *
     * @return the value of APPL_CHG_CNCL.MOD_DATE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG_CNCL.MOD_DATE
     *
     * @param modDate the value for APPL_CHG_CNCL.MOD_DATE
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}