package com.apexsoft.ysprj.applicants.application.domain;

import java.util.Date;

public class ApplicationExperience extends ApplicationExperienceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.JOIN_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String joinDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.RETR_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String retrDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.CORP_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.EXPR_DESC
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String exprDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.CRE_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.CRE_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.MOD_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_EXPR.MOD_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.JOIN_DAY
     *
     * @return the value of APPL_EXPR.JOIN_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getJoinDay() {
        return joinDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.JOIN_DAY
     *
     * @param joinDay the value for APPL_EXPR.JOIN_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setJoinDay(String joinDay) {
        this.joinDay = joinDay == null ? null : joinDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.RETR_DAY
     *
     * @return the value of APPL_EXPR.RETR_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getRetrDay() {
        return retrDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.RETR_DAY
     *
     * @param retrDay the value for APPL_EXPR.RETR_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setRetrDay(String retrDay) {
        this.retrDay = retrDay == null ? null : retrDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.CORP_NAME
     *
     * @return the value of APPL_EXPR.CORP_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.CORP_NAME
     *
     * @param corpName the value for APPL_EXPR.CORP_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.EXPR_DESC
     *
     * @return the value of APPL_EXPR.EXPR_DESC
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getExprDesc() {
        return exprDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.EXPR_DESC
     *
     * @param exprDesc the value for APPL_EXPR.EXPR_DESC
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setExprDesc(String exprDesc) {
        this.exprDesc = exprDesc == null ? null : exprDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.CRE_ID
     *
     * @return the value of APPL_EXPR.CRE_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.CRE_ID
     *
     * @param creId the value for APPL_EXPR.CRE_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.CRE_DATE
     *
     * @return the value of APPL_EXPR.CRE_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.CRE_DATE
     *
     * @param creDate the value for APPL_EXPR.CRE_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.MOD_ID
     *
     * @return the value of APPL_EXPR.MOD_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.MOD_ID
     *
     * @param modId the value for APPL_EXPR.MOD_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_EXPR.MOD_DATE
     *
     * @return the value of APPL_EXPR.MOD_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_EXPR.MOD_DATE
     *
     * @param modDate the value for APPL_EXPR.MOD_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}