package com.apexsoft.ysprj.applicants.application.domain;

import java.util.Date;

public class Application {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.APPL_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private Integer applNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.USER_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ADMS_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String admsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ENTR_YEAR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String entrYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ADMS_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String admsTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.APPL_ATTR_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String applAttrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.FORN_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String fornTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.CAMP_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String campCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.COLL_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String collCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.DEPT_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ARI_INST_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String ariInstCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.CORS_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String corsTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.DETL_MAJ_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String detlMajCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.INP_DETL_MAJ
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String inpDetlMaj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.PART_TIME_YN
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String partTimeYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.KOR_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String korName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.CHN_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String chnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ENG_SUR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String engSur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ENG_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String engName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.RGST_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String rgstNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.RGST_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String rgstBornDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.RGST_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String rgstEncr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.CITZ_CNTR_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String citzCntrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.BORN_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String bornDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.GEND
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String gend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ZIP_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.DETL_ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String detlAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.TEL_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String telNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.MOBI_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String mobiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.FAX_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String faxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.MAIL_ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String mailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.APPL_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String applId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.APPL_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private Date applDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.APPL_STS_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String applStsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.PRIV_INFO_YN
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String privInfoYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.CRE_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.CRE_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.MOD_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL.MOD_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.APPL_NO
     *
     * @return the value of APPL.APPL_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public Integer getApplNo() {
        return applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.APPL_NO
     *
     * @param applNo the value for APPL.APPL_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setApplNo(Integer applNo) {
        this.applNo = applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.USER_ID
     *
     * @return the value of APPL.USER_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.USER_ID
     *
     * @param userId the value for APPL.USER_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ADMS_NO
     *
     * @return the value of APPL.ADMS_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getAdmsNo() {
        return admsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ADMS_NO
     *
     * @param admsNo the value for APPL.ADMS_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setAdmsNo(String admsNo) {
        this.admsNo = admsNo == null ? null : admsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ENTR_YEAR
     *
     * @return the value of APPL.ENTR_YEAR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getEntrYear() {
        return entrYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ENTR_YEAR
     *
     * @param entrYear the value for APPL.ENTR_YEAR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setEntrYear(String entrYear) {
        this.entrYear = entrYear == null ? null : entrYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ADMS_TYPE_CODE
     *
     * @return the value of APPL.ADMS_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getAdmsTypeCode() {
        return admsTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ADMS_TYPE_CODE
     *
     * @param admsTypeCode the value for APPL.ADMS_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setAdmsTypeCode(String admsTypeCode) {
        this.admsTypeCode = admsTypeCode == null ? null : admsTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.APPL_ATTR_CODE
     *
     * @return the value of APPL.APPL_ATTR_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getApplAttrCode() {
        return applAttrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.APPL_ATTR_CODE
     *
     * @param applAttrCode the value for APPL.APPL_ATTR_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setApplAttrCode(String applAttrCode) {
        this.applAttrCode = applAttrCode == null ? null : applAttrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.FORN_TYPE_CODE
     *
     * @return the value of APPL.FORN_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getFornTypeCode() {
        return fornTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.FORN_TYPE_CODE
     *
     * @param fornTypeCode the value for APPL.FORN_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setFornTypeCode(String fornTypeCode) {
        this.fornTypeCode = fornTypeCode == null ? null : fornTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.CAMP_CODE
     *
     * @return the value of APPL.CAMP_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getCampCode() {
        return campCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.CAMP_CODE
     *
     * @param campCode the value for APPL.CAMP_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCampCode(String campCode) {
        this.campCode = campCode == null ? null : campCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.COLL_CODE
     *
     * @return the value of APPL.COLL_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getCollCode() {
        return collCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.COLL_CODE
     *
     * @param collCode the value for APPL.COLL_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCollCode(String collCode) {
        this.collCode = collCode == null ? null : collCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.DEPT_CODE
     *
     * @return the value of APPL.DEPT_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.DEPT_CODE
     *
     * @param deptCode the value for APPL.DEPT_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ARI_INST_CODE
     *
     * @return the value of APPL.ARI_INST_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getAriInstCode() {
        return ariInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ARI_INST_CODE
     *
     * @param ariInstCode the value for APPL.ARI_INST_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setAriInstCode(String ariInstCode) {
        this.ariInstCode = ariInstCode == null ? null : ariInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.CORS_TYPE_CODE
     *
     * @return the value of APPL.CORS_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getCorsTypeCode() {
        return corsTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.CORS_TYPE_CODE
     *
     * @param corsTypeCode the value for APPL.CORS_TYPE_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCorsTypeCode(String corsTypeCode) {
        this.corsTypeCode = corsTypeCode == null ? null : corsTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.DETL_MAJ_CODE
     *
     * @return the value of APPL.DETL_MAJ_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getDetlMajCode() {
        return detlMajCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.DETL_MAJ_CODE
     *
     * @param detlMajCode the value for APPL.DETL_MAJ_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setDetlMajCode(String detlMajCode) {
        this.detlMajCode = detlMajCode == null ? null : detlMajCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.INP_DETL_MAJ
     *
     * @return the value of APPL.INP_DETL_MAJ
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getInpDetlMaj() {
        return inpDetlMaj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.INP_DETL_MAJ
     *
     * @param inpDetlMaj the value for APPL.INP_DETL_MAJ
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setInpDetlMaj(String inpDetlMaj) {
        this.inpDetlMaj = inpDetlMaj == null ? null : inpDetlMaj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.PART_TIME_YN
     *
     * @return the value of APPL.PART_TIME_YN
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getPartTimeYn() {
        return partTimeYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.PART_TIME_YN
     *
     * @param partTimeYn the value for APPL.PART_TIME_YN
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setPartTimeYn(String partTimeYn) {
        this.partTimeYn = partTimeYn == null ? null : partTimeYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.KOR_NAME
     *
     * @return the value of APPL.KOR_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getKorName() {
        return korName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.KOR_NAME
     *
     * @param korName the value for APPL.KOR_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setKorName(String korName) {
        this.korName = korName == null ? null : korName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.CHN_NAME
     *
     * @return the value of APPL.CHN_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getChnName() {
        return chnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.CHN_NAME
     *
     * @param chnName the value for APPL.CHN_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setChnName(String chnName) {
        this.chnName = chnName == null ? null : chnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ENG_SUR
     *
     * @return the value of APPL.ENG_SUR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getEngSur() {
        return engSur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ENG_SUR
     *
     * @param engSur the value for APPL.ENG_SUR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setEngSur(String engSur) {
        this.engSur = engSur == null ? null : engSur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ENG_NAME
     *
     * @return the value of APPL.ENG_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ENG_NAME
     *
     * @param engName the value for APPL.ENG_NAME
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.RGST_NO
     *
     * @return the value of APPL.RGST_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getRgstNo() {
        return rgstNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.RGST_NO
     *
     * @param rgstNo the value for APPL.RGST_NO
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setRgstNo(String rgstNo) {
        this.rgstNo = rgstNo == null ? null : rgstNo.trim();
    }

    public String getRgstBornDate() {
        return rgstBornDate;
    }

    public void setRgstBornDate(String rgstBornDate) {
        this.rgstBornDate = rgstBornDate;
    }

    public String getRgstEncr() {
        return rgstEncr;
    }

    public void setRgstEncr(String rgstEncr) {
        this.rgstEncr = rgstEncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.CITZ_CNTR_CODE
     *
     * @return the value of APPL.CITZ_CNTR_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getCitzCntrCode() {
        return citzCntrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.CITZ_CNTR_CODE
     *
     * @param citzCntrCode the value for APPL.CITZ_CNTR_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCitzCntrCode(String citzCntrCode) {
        this.citzCntrCode = citzCntrCode == null ? null : citzCntrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.BORN_DAY
     *
     * @return the value of APPL.BORN_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getBornDay() {
        return bornDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.BORN_DAY
     *
     * @param bornDay the value for APPL.BORN_DAY
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setBornDay(String bornDay) {
        this.bornDay = bornDay == null ? null : bornDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.GEND
     *
     * @return the value of APPL.GEND
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getGend() {
        return gend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.GEND
     *
     * @param gend the value for APPL.GEND
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setGend(String gend) {
        this.gend = gend == null ? null : gend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ZIP_CODE
     *
     * @return the value of APPL.ZIP_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ZIP_CODE
     *
     * @param zipCode the value for APPL.ZIP_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.ADDR
     *
     * @return the value of APPL.ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.ADDR
     *
     * @param addr the value for APPL.ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.DETL_ADDR
     *
     * @return the value of APPL.DETL_ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getDetlAddr() {
        return detlAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.DETL_ADDR
     *
     * @param detlAddr the value for APPL.DETL_ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setDetlAddr(String detlAddr) {
        this.detlAddr = detlAddr == null ? null : detlAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.TEL_NUM
     *
     * @return the value of APPL.TEL_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getTelNum() {
        return telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.TEL_NUM
     *
     * @param telNum the value for APPL.TEL_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setTelNum(String telNum) {
        this.telNum = telNum == null ? null : telNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.MOBI_NUM
     *
     * @return the value of APPL.MOBI_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getMobiNum() {
        return mobiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.MOBI_NUM
     *
     * @param mobiNum the value for APPL.MOBI_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setMobiNum(String mobiNum) {
        this.mobiNum = mobiNum == null ? null : mobiNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.FAX_NUM
     *
     * @return the value of APPL.FAX_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getFaxNum() {
        return faxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.FAX_NUM
     *
     * @param faxNum the value for APPL.FAX_NUM
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setFaxNum(String faxNum) {
        this.faxNum = faxNum == null ? null : faxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.MAIL_ADDR
     *
     * @return the value of APPL.MAIL_ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getMailAddr() {
        return mailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.MAIL_ADDR
     *
     * @param mailAddr the value for APPL.MAIL_ADDR
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setMailAddr(String mailAddr) {
        this.mailAddr = mailAddr == null ? null : mailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.APPL_ID
     *
     * @return the value of APPL.APPL_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getApplId() {
        return applId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.APPL_ID
     *
     * @param applId the value for APPL.APPL_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setApplId(String applId) {
        this.applId = applId == null ? null : applId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.APPL_DATE
     *
     * @return the value of APPL.APPL_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public Date getApplDate() {
        return applDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.APPL_DATE
     *
     * @param applDate the value for APPL.APPL_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setApplDate(Date applDate) {
        this.applDate = applDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.APPL_STS_CODE
     *
     * @return the value of APPL.APPL_STS_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getApplStsCode() {
        return applStsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.APPL_STS_CODE
     *
     * @param applStsCode the value for APPL.APPL_STS_CODE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setApplStsCode(String applStsCode) {
        this.applStsCode = applStsCode == null ? null : applStsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.PRIV_INFO_YN
     *
     * @return the value of APPL.PRIV_INFO_YN
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getPrivInfoYn() {
        return privInfoYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.PRIV_INFO_YN
     *
     * @param privInfoYn the value for APPL.PRIV_INFO_YN
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setPrivInfoYn(String privInfoYn) {
        this.privInfoYn = privInfoYn == null ? null : privInfoYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.CRE_ID
     *
     * @return the value of APPL.CRE_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.CRE_ID
     *
     * @param creId the value for APPL.CRE_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.CRE_DATE
     *
     * @return the value of APPL.CRE_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.CRE_DATE
     *
     * @param creDate the value for APPL.CRE_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.MOD_ID
     *
     * @return the value of APPL.MOD_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.MOD_ID
     *
     * @param modId the value for APPL.MOD_ID
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL.MOD_DATE
     *
     * @return the value of APPL.MOD_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL.MOD_DATE
     *
     * @param modDate the value for APPL.MOD_DATE
     *
     * @mbggenerated Thu Sep 18 18:37:48 KST 2014
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}