package com.apexsoft.ysprj.applicants.application.domain;

public class ApplicationETCWithBLOBs extends ApplicationETC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_ETC.COV_LETT
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String covLett;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_ETC.STUD_PLAN
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    private String studPlan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_ETC.COV_LETT
     *
     * @return the value of APPL_ETC.COV_LETT
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getCovLett() {
        return covLett;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_ETC.COV_LETT
     *
     * @param covLett the value for APPL_ETC.COV_LETT
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setCovLett(String covLett) {
        this.covLett = covLett == null ? null : covLett.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_ETC.STUD_PLAN
     *
     * @return the value of APPL_ETC.STUD_PLAN
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getStudPlan() {
        return studPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_ETC.STUD_PLAN
     *
     * @param studPlan the value for APPL_ETC.STUD_PLAN
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setStudPlan(String studPlan) {
        this.studPlan = studPlan == null ? null : studPlan.trim();
    }
}