package com.apexsoft.ysprj.applicants.application.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApplicationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public ApplicationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApplNoIsNull() {
            addCriterion("APPL_NO is null");
            return (Criteria) this;
        }

        public Criteria andApplNoIsNotNull() {
            addCriterion("APPL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andApplNoEqualTo(Integer value) {
            addCriterion("APPL_NO =", value, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoNotEqualTo(Integer value) {
            addCriterion("APPL_NO <>", value, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoGreaterThan(Integer value) {
            addCriterion("APPL_NO >", value, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("APPL_NO >=", value, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoLessThan(Integer value) {
            addCriterion("APPL_NO <", value, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoLessThanOrEqualTo(Integer value) {
            addCriterion("APPL_NO <=", value, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoIn(List<Integer> values) {
            addCriterion("APPL_NO in", values, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoNotIn(List<Integer> values) {
            addCriterion("APPL_NO not in", values, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoBetween(Integer value1, Integer value2) {
            addCriterion("APPL_NO between", value1, value2, "applNo");
            return (Criteria) this;
        }

        public Criteria andApplNoNotBetween(Integer value1, Integer value2) {
            addCriterion("APPL_NO not between", value1, value2, "applNo");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAdmsNoIsNull() {
            addCriterion("ADMS_NO is null");
            return (Criteria) this;
        }

        public Criteria andAdmsNoIsNotNull() {
            addCriterion("ADMS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAdmsNoEqualTo(String value) {
            addCriterion("ADMS_NO =", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoNotEqualTo(String value) {
            addCriterion("ADMS_NO <>", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoGreaterThan(String value) {
            addCriterion("ADMS_NO >", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoGreaterThanOrEqualTo(String value) {
            addCriterion("ADMS_NO >=", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoLessThan(String value) {
            addCriterion("ADMS_NO <", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoLessThanOrEqualTo(String value) {
            addCriterion("ADMS_NO <=", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoLike(String value) {
            addCriterion("ADMS_NO like", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoNotLike(String value) {
            addCriterion("ADMS_NO not like", value, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoIn(List<String> values) {
            addCriterion("ADMS_NO in", values, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoNotIn(List<String> values) {
            addCriterion("ADMS_NO not in", values, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoBetween(String value1, String value2) {
            addCriterion("ADMS_NO between", value1, value2, "admsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsNoNotBetween(String value1, String value2) {
            addCriterion("ADMS_NO not between", value1, value2, "admsNo");
            return (Criteria) this;
        }

        public Criteria andEntrYearIsNull() {
            addCriterion("ENTR_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andEntrYearIsNotNull() {
            addCriterion("ENTR_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andEntrYearEqualTo(String value) {
            addCriterion("ENTR_YEAR =", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearNotEqualTo(String value) {
            addCriterion("ENTR_YEAR <>", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearGreaterThan(String value) {
            addCriterion("ENTR_YEAR >", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearGreaterThanOrEqualTo(String value) {
            addCriterion("ENTR_YEAR >=", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearLessThan(String value) {
            addCriterion("ENTR_YEAR <", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearLessThanOrEqualTo(String value) {
            addCriterion("ENTR_YEAR <=", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearLike(String value) {
            addCriterion("ENTR_YEAR like", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearNotLike(String value) {
            addCriterion("ENTR_YEAR not like", value, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearIn(List<String> values) {
            addCriterion("ENTR_YEAR in", values, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearNotIn(List<String> values) {
            addCriterion("ENTR_YEAR not in", values, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearBetween(String value1, String value2) {
            addCriterion("ENTR_YEAR between", value1, value2, "entrYear");
            return (Criteria) this;
        }

        public Criteria andEntrYearNotBetween(String value1, String value2) {
            addCriterion("ENTR_YEAR not between", value1, value2, "entrYear");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeIsNull() {
            addCriterion("ADMS_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeIsNotNull() {
            addCriterion("ADMS_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeEqualTo(String value) {
            addCriterion("ADMS_TYPE_CODE =", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeNotEqualTo(String value) {
            addCriterion("ADMS_TYPE_CODE <>", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeGreaterThan(String value) {
            addCriterion("ADMS_TYPE_CODE >", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ADMS_TYPE_CODE >=", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeLessThan(String value) {
            addCriterion("ADMS_TYPE_CODE <", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("ADMS_TYPE_CODE <=", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeLike(String value) {
            addCriterion("ADMS_TYPE_CODE like", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeNotLike(String value) {
            addCriterion("ADMS_TYPE_CODE not like", value, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeIn(List<String> values) {
            addCriterion("ADMS_TYPE_CODE in", values, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeNotIn(List<String> values) {
            addCriterion("ADMS_TYPE_CODE not in", values, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeBetween(String value1, String value2) {
            addCriterion("ADMS_TYPE_CODE between", value1, value2, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andAdmsTypeCodeNotBetween(String value1, String value2) {
            addCriterion("ADMS_TYPE_CODE not between", value1, value2, "admsTypeCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeIsNull() {
            addCriterion("APPL_ATTR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeIsNotNull() {
            addCriterion("APPL_ATTR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeEqualTo(String value) {
            addCriterion("APPL_ATTR_CODE =", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeNotEqualTo(String value) {
            addCriterion("APPL_ATTR_CODE <>", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeGreaterThan(String value) {
            addCriterion("APPL_ATTR_CODE >", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("APPL_ATTR_CODE >=", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeLessThan(String value) {
            addCriterion("APPL_ATTR_CODE <", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeLessThanOrEqualTo(String value) {
            addCriterion("APPL_ATTR_CODE <=", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeLike(String value) {
            addCriterion("APPL_ATTR_CODE like", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeNotLike(String value) {
            addCriterion("APPL_ATTR_CODE not like", value, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeIn(List<String> values) {
            addCriterion("APPL_ATTR_CODE in", values, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeNotIn(List<String> values) {
            addCriterion("APPL_ATTR_CODE not in", values, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeBetween(String value1, String value2) {
            addCriterion("APPL_ATTR_CODE between", value1, value2, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andApplAttrCodeNotBetween(String value1, String value2) {
            addCriterion("APPL_ATTR_CODE not between", value1, value2, "applAttrCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeIsNull() {
            addCriterion("FORN_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeIsNotNull() {
            addCriterion("FORN_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeEqualTo(String value) {
            addCriterion("FORN_TYPE_CODE =", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeNotEqualTo(String value) {
            addCriterion("FORN_TYPE_CODE <>", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeGreaterThan(String value) {
            addCriterion("FORN_TYPE_CODE >", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FORN_TYPE_CODE >=", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeLessThan(String value) {
            addCriterion("FORN_TYPE_CODE <", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("FORN_TYPE_CODE <=", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeLike(String value) {
            addCriterion("FORN_TYPE_CODE like", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeNotLike(String value) {
            addCriterion("FORN_TYPE_CODE not like", value, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeIn(List<String> values) {
            addCriterion("FORN_TYPE_CODE in", values, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeNotIn(List<String> values) {
            addCriterion("FORN_TYPE_CODE not in", values, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeBetween(String value1, String value2) {
            addCriterion("FORN_TYPE_CODE between", value1, value2, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andFornTypeCodeNotBetween(String value1, String value2) {
            addCriterion("FORN_TYPE_CODE not between", value1, value2, "fornTypeCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeIsNull() {
            addCriterion("CAMP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCampCodeIsNotNull() {
            addCriterion("CAMP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCampCodeEqualTo(String value) {
            addCriterion("CAMP_CODE =", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeNotEqualTo(String value) {
            addCriterion("CAMP_CODE <>", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeGreaterThan(String value) {
            addCriterion("CAMP_CODE >", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CAMP_CODE >=", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeLessThan(String value) {
            addCriterion("CAMP_CODE <", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeLessThanOrEqualTo(String value) {
            addCriterion("CAMP_CODE <=", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeLike(String value) {
            addCriterion("CAMP_CODE like", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeNotLike(String value) {
            addCriterion("CAMP_CODE not like", value, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeIn(List<String> values) {
            addCriterion("CAMP_CODE in", values, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeNotIn(List<String> values) {
            addCriterion("CAMP_CODE not in", values, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeBetween(String value1, String value2) {
            addCriterion("CAMP_CODE between", value1, value2, "campCode");
            return (Criteria) this;
        }

        public Criteria andCampCodeNotBetween(String value1, String value2) {
            addCriterion("CAMP_CODE not between", value1, value2, "campCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeIsNull() {
            addCriterion("COLL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCollCodeIsNotNull() {
            addCriterion("COLL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCollCodeEqualTo(String value) {
            addCriterion("COLL_CODE =", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeNotEqualTo(String value) {
            addCriterion("COLL_CODE <>", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeGreaterThan(String value) {
            addCriterion("COLL_CODE >", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeGreaterThanOrEqualTo(String value) {
            addCriterion("COLL_CODE >=", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeLessThan(String value) {
            addCriterion("COLL_CODE <", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeLessThanOrEqualTo(String value) {
            addCriterion("COLL_CODE <=", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeLike(String value) {
            addCriterion("COLL_CODE like", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeNotLike(String value) {
            addCriterion("COLL_CODE not like", value, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeIn(List<String> values) {
            addCriterion("COLL_CODE in", values, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeNotIn(List<String> values) {
            addCriterion("COLL_CODE not in", values, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeBetween(String value1, String value2) {
            addCriterion("COLL_CODE between", value1, value2, "collCode");
            return (Criteria) this;
        }

        public Criteria andCollCodeNotBetween(String value1, String value2) {
            addCriterion("COLL_CODE not between", value1, value2, "collCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNull() {
            addCriterion("DEPT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNotNull() {
            addCriterion("DEPT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeEqualTo(String value) {
            addCriterion("DEPT_CODE =", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotEqualTo(String value) {
            addCriterion("DEPT_CODE <>", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThan(String value) {
            addCriterion("DEPT_CODE >", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_CODE >=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThan(String value) {
            addCriterion("DEPT_CODE <", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThanOrEqualTo(String value) {
            addCriterion("DEPT_CODE <=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLike(String value) {
            addCriterion("DEPT_CODE like", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotLike(String value) {
            addCriterion("DEPT_CODE not like", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIn(List<String> values) {
            addCriterion("DEPT_CODE in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotIn(List<String> values) {
            addCriterion("DEPT_CODE not in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeBetween(String value1, String value2) {
            addCriterion("DEPT_CODE between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotBetween(String value1, String value2) {
            addCriterion("DEPT_CODE not between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeIsNull() {
            addCriterion("ARI_INST_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeIsNotNull() {
            addCriterion("ARI_INST_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeEqualTo(String value) {
            addCriterion("ARI_INST_CODE =", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeNotEqualTo(String value) {
            addCriterion("ARI_INST_CODE <>", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeGreaterThan(String value) {
            addCriterion("ARI_INST_CODE >", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ARI_INST_CODE >=", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeLessThan(String value) {
            addCriterion("ARI_INST_CODE <", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeLessThanOrEqualTo(String value) {
            addCriterion("ARI_INST_CODE <=", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeLike(String value) {
            addCriterion("ARI_INST_CODE like", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeNotLike(String value) {
            addCriterion("ARI_INST_CODE not like", value, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeIn(List<String> values) {
            addCriterion("ARI_INST_CODE in", values, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeNotIn(List<String> values) {
            addCriterion("ARI_INST_CODE not in", values, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeBetween(String value1, String value2) {
            addCriterion("ARI_INST_CODE between", value1, value2, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andAriInstCodeNotBetween(String value1, String value2) {
            addCriterion("ARI_INST_CODE not between", value1, value2, "ariInstCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeIsNull() {
            addCriterion("CORS_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeIsNotNull() {
            addCriterion("CORS_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeEqualTo(String value) {
            addCriterion("CORS_TYPE_CODE =", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeNotEqualTo(String value) {
            addCriterion("CORS_TYPE_CODE <>", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeGreaterThan(String value) {
            addCriterion("CORS_TYPE_CODE >", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CORS_TYPE_CODE >=", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeLessThan(String value) {
            addCriterion("CORS_TYPE_CODE <", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("CORS_TYPE_CODE <=", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeLike(String value) {
            addCriterion("CORS_TYPE_CODE like", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeNotLike(String value) {
            addCriterion("CORS_TYPE_CODE not like", value, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeIn(List<String> values) {
            addCriterion("CORS_TYPE_CODE in", values, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeNotIn(List<String> values) {
            addCriterion("CORS_TYPE_CODE not in", values, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeBetween(String value1, String value2) {
            addCriterion("CORS_TYPE_CODE between", value1, value2, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andCorsTypeCodeNotBetween(String value1, String value2) {
            addCriterion("CORS_TYPE_CODE not between", value1, value2, "corsTypeCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeIsNull() {
            addCriterion("DETL_MAJ_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeIsNotNull() {
            addCriterion("DETL_MAJ_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE =", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE <>", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeGreaterThan(String value) {
            addCriterion("DETL_MAJ_CODE >", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE >=", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeLessThan(String value) {
            addCriterion("DETL_MAJ_CODE <", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeLessThanOrEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE <=", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeLike(String value) {
            addCriterion("DETL_MAJ_CODE like", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotLike(String value) {
            addCriterion("DETL_MAJ_CODE not like", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeIn(List<String> values) {
            addCriterion("DETL_MAJ_CODE in", values, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotIn(List<String> values) {
            addCriterion("DETL_MAJ_CODE not in", values, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeBetween(String value1, String value2) {
            addCriterion("DETL_MAJ_CODE between", value1, value2, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotBetween(String value1, String value2) {
            addCriterion("DETL_MAJ_CODE not between", value1, value2, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajIsNull() {
            addCriterion("INP_DETL_MAJ is null");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajIsNotNull() {
            addCriterion("INP_DETL_MAJ is not null");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajEqualTo(String value) {
            addCriterion("INP_DETL_MAJ =", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajNotEqualTo(String value) {
            addCriterion("INP_DETL_MAJ <>", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajGreaterThan(String value) {
            addCriterion("INP_DETL_MAJ >", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajGreaterThanOrEqualTo(String value) {
            addCriterion("INP_DETL_MAJ >=", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajLessThan(String value) {
            addCriterion("INP_DETL_MAJ <", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajLessThanOrEqualTo(String value) {
            addCriterion("INP_DETL_MAJ <=", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajLike(String value) {
            addCriterion("INP_DETL_MAJ like", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajNotLike(String value) {
            addCriterion("INP_DETL_MAJ not like", value, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajIn(List<String> values) {
            addCriterion("INP_DETL_MAJ in", values, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajNotIn(List<String> values) {
            addCriterion("INP_DETL_MAJ not in", values, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajBetween(String value1, String value2) {
            addCriterion("INP_DETL_MAJ between", value1, value2, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andInpDetlMajNotBetween(String value1, String value2) {
            addCriterion("INP_DETL_MAJ not between", value1, value2, "inpDetlMaj");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnIsNull() {
            addCriterion("PART_TIME_YN is null");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnIsNotNull() {
            addCriterion("PART_TIME_YN is not null");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnEqualTo(String value) {
            addCriterion("PART_TIME_YN =", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnNotEqualTo(String value) {
            addCriterion("PART_TIME_YN <>", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnGreaterThan(String value) {
            addCriterion("PART_TIME_YN >", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnGreaterThanOrEqualTo(String value) {
            addCriterion("PART_TIME_YN >=", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnLessThan(String value) {
            addCriterion("PART_TIME_YN <", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnLessThanOrEqualTo(String value) {
            addCriterion("PART_TIME_YN <=", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnLike(String value) {
            addCriterion("PART_TIME_YN like", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnNotLike(String value) {
            addCriterion("PART_TIME_YN not like", value, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnIn(List<String> values) {
            addCriterion("PART_TIME_YN in", values, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnNotIn(List<String> values) {
            addCriterion("PART_TIME_YN not in", values, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnBetween(String value1, String value2) {
            addCriterion("PART_TIME_YN between", value1, value2, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andPartTimeYnNotBetween(String value1, String value2) {
            addCriterion("PART_TIME_YN not between", value1, value2, "partTimeYn");
            return (Criteria) this;
        }

        public Criteria andKorNameIsNull() {
            addCriterion("KOR_NAME is null");
            return (Criteria) this;
        }

        public Criteria andKorNameIsNotNull() {
            addCriterion("KOR_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andKorNameEqualTo(String value) {
            addCriterion("KOR_NAME =", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameNotEqualTo(String value) {
            addCriterion("KOR_NAME <>", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameGreaterThan(String value) {
            addCriterion("KOR_NAME >", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameGreaterThanOrEqualTo(String value) {
            addCriterion("KOR_NAME >=", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameLessThan(String value) {
            addCriterion("KOR_NAME <", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameLessThanOrEqualTo(String value) {
            addCriterion("KOR_NAME <=", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameLike(String value) {
            addCriterion("KOR_NAME like", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameNotLike(String value) {
            addCriterion("KOR_NAME not like", value, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameIn(List<String> values) {
            addCriterion("KOR_NAME in", values, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameNotIn(List<String> values) {
            addCriterion("KOR_NAME not in", values, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameBetween(String value1, String value2) {
            addCriterion("KOR_NAME between", value1, value2, "korName");
            return (Criteria) this;
        }

        public Criteria andKorNameNotBetween(String value1, String value2) {
            addCriterion("KOR_NAME not between", value1, value2, "korName");
            return (Criteria) this;
        }

        public Criteria andChnNameIsNull() {
            addCriterion("CHN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andChnNameIsNotNull() {
            addCriterion("CHN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andChnNameEqualTo(String value) {
            addCriterion("CHN_NAME =", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameNotEqualTo(String value) {
            addCriterion("CHN_NAME <>", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameGreaterThan(String value) {
            addCriterion("CHN_NAME >", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHN_NAME >=", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameLessThan(String value) {
            addCriterion("CHN_NAME <", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameLessThanOrEqualTo(String value) {
            addCriterion("CHN_NAME <=", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameLike(String value) {
            addCriterion("CHN_NAME like", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameNotLike(String value) {
            addCriterion("CHN_NAME not like", value, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameIn(List<String> values) {
            addCriterion("CHN_NAME in", values, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameNotIn(List<String> values) {
            addCriterion("CHN_NAME not in", values, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameBetween(String value1, String value2) {
            addCriterion("CHN_NAME between", value1, value2, "chnName");
            return (Criteria) this;
        }

        public Criteria andChnNameNotBetween(String value1, String value2) {
            addCriterion("CHN_NAME not between", value1, value2, "chnName");
            return (Criteria) this;
        }

        public Criteria andEngSurIsNull() {
            addCriterion("ENG_SUR is null");
            return (Criteria) this;
        }

        public Criteria andEngSurIsNotNull() {
            addCriterion("ENG_SUR is not null");
            return (Criteria) this;
        }

        public Criteria andEngSurEqualTo(String value) {
            addCriterion("ENG_SUR =", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurNotEqualTo(String value) {
            addCriterion("ENG_SUR <>", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurGreaterThan(String value) {
            addCriterion("ENG_SUR >", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurGreaterThanOrEqualTo(String value) {
            addCriterion("ENG_SUR >=", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurLessThan(String value) {
            addCriterion("ENG_SUR <", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurLessThanOrEqualTo(String value) {
            addCriterion("ENG_SUR <=", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurLike(String value) {
            addCriterion("ENG_SUR like", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurNotLike(String value) {
            addCriterion("ENG_SUR not like", value, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurIn(List<String> values) {
            addCriterion("ENG_SUR in", values, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurNotIn(List<String> values) {
            addCriterion("ENG_SUR not in", values, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurBetween(String value1, String value2) {
            addCriterion("ENG_SUR between", value1, value2, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngSurNotBetween(String value1, String value2) {
            addCriterion("ENG_SUR not between", value1, value2, "engSur");
            return (Criteria) this;
        }

        public Criteria andEngNameIsNull() {
            addCriterion("ENG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEngNameIsNotNull() {
            addCriterion("ENG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEngNameEqualTo(String value) {
            addCriterion("ENG_NAME =", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotEqualTo(String value) {
            addCriterion("ENG_NAME <>", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameGreaterThan(String value) {
            addCriterion("ENG_NAME >", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameGreaterThanOrEqualTo(String value) {
            addCriterion("ENG_NAME >=", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameLessThan(String value) {
            addCriterion("ENG_NAME <", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameLessThanOrEqualTo(String value) {
            addCriterion("ENG_NAME <=", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameLike(String value) {
            addCriterion("ENG_NAME like", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotLike(String value) {
            addCriterion("ENG_NAME not like", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameIn(List<String> values) {
            addCriterion("ENG_NAME in", values, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotIn(List<String> values) {
            addCriterion("ENG_NAME not in", values, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameBetween(String value1, String value2) {
            addCriterion("ENG_NAME between", value1, value2, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotBetween(String value1, String value2) {
            addCriterion("ENG_NAME not between", value1, value2, "engName");
            return (Criteria) this;
        }

        public Criteria andRgstNoIsNull() {
            addCriterion("RGST_NO is null");
            return (Criteria) this;
        }

        public Criteria andRgstNoIsNotNull() {
            addCriterion("RGST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRgstNoEqualTo(String value) {
            addCriterion("RGST_NO =", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoNotEqualTo(String value) {
            addCriterion("RGST_NO <>", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoGreaterThan(String value) {
            addCriterion("RGST_NO >", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoGreaterThanOrEqualTo(String value) {
            addCriterion("RGST_NO >=", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoLessThan(String value) {
            addCriterion("RGST_NO <", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoLessThanOrEqualTo(String value) {
            addCriterion("RGST_NO <=", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoLike(String value) {
            addCriterion("RGST_NO like", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoNotLike(String value) {
            addCriterion("RGST_NO not like", value, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoIn(List<String> values) {
            addCriterion("RGST_NO in", values, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoNotIn(List<String> values) {
            addCriterion("RGST_NO not in", values, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoBetween(String value1, String value2) {
            addCriterion("RGST_NO between", value1, value2, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andRgstNoNotBetween(String value1, String value2) {
            addCriterion("RGST_NO not between", value1, value2, "rgstNo");
            return (Criteria) this;
        }

        public Criteria andBornDayIsNull() {
            addCriterion("BORN_DAY is null");
            return (Criteria) this;
        }

        public Criteria andBornDayIsNotNull() {
            addCriterion("BORN_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andBornDayEqualTo(String value) {
            addCriterion("BORN_DAY =", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayNotEqualTo(String value) {
            addCriterion("BORN_DAY <>", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayGreaterThan(String value) {
            addCriterion("BORN_DAY >", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayGreaterThanOrEqualTo(String value) {
            addCriterion("BORN_DAY >=", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayLessThan(String value) {
            addCriterion("BORN_DAY <", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayLessThanOrEqualTo(String value) {
            addCriterion("BORN_DAY <=", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayLike(String value) {
            addCriterion("BORN_DAY like", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayNotLike(String value) {
            addCriterion("BORN_DAY not like", value, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayIn(List<String> values) {
            addCriterion("BORN_DAY in", values, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayNotIn(List<String> values) {
            addCriterion("BORN_DAY not in", values, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayBetween(String value1, String value2) {
            addCriterion("BORN_DAY between", value1, value2, "bornDay");
            return (Criteria) this;
        }

        public Criteria andBornDayNotBetween(String value1, String value2) {
            addCriterion("BORN_DAY not between", value1, value2, "bornDay");
            return (Criteria) this;
        }

        public Criteria andGendIsNull() {
            addCriterion("GEND is null");
            return (Criteria) this;
        }

        public Criteria andGendIsNotNull() {
            addCriterion("GEND is not null");
            return (Criteria) this;
        }

        public Criteria andGendEqualTo(String value) {
            addCriterion("GEND =", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendNotEqualTo(String value) {
            addCriterion("GEND <>", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendGreaterThan(String value) {
            addCriterion("GEND >", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendGreaterThanOrEqualTo(String value) {
            addCriterion("GEND >=", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendLessThan(String value) {
            addCriterion("GEND <", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendLessThanOrEqualTo(String value) {
            addCriterion("GEND <=", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendLike(String value) {
            addCriterion("GEND like", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendNotLike(String value) {
            addCriterion("GEND not like", value, "gend");
            return (Criteria) this;
        }

        public Criteria andGendIn(List<String> values) {
            addCriterion("GEND in", values, "gend");
            return (Criteria) this;
        }

        public Criteria andGendNotIn(List<String> values) {
            addCriterion("GEND not in", values, "gend");
            return (Criteria) this;
        }

        public Criteria andGendBetween(String value1, String value2) {
            addCriterion("GEND between", value1, value2, "gend");
            return (Criteria) this;
        }

        public Criteria andGendNotBetween(String value1, String value2) {
            addCriterion("GEND not between", value1, value2, "gend");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNull() {
            addCriterion("ZIP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNotNull() {
            addCriterion("ZIP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andZipCodeEqualTo(String value) {
            addCriterion("ZIP_CODE =", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotEqualTo(String value) {
            addCriterion("ZIP_CODE <>", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThan(String value) {
            addCriterion("ZIP_CODE >", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE >=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThan(String value) {
            addCriterion("ZIP_CODE <", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE <=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLike(String value) {
            addCriterion("ZIP_CODE like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotLike(String value) {
            addCriterion("ZIP_CODE not like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeIn(List<String> values) {
            addCriterion("ZIP_CODE in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotIn(List<String> values) {
            addCriterion("ZIP_CODE not in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeBetween(String value1, String value2) {
            addCriterion("ZIP_CODE between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotBetween(String value1, String value2) {
            addCriterion("ZIP_CODE not between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andAddrIsNull() {
            addCriterion("ADDR is null");
            return (Criteria) this;
        }

        public Criteria andAddrIsNotNull() {
            addCriterion("ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andAddrEqualTo(String value) {
            addCriterion("ADDR =", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotEqualTo(String value) {
            addCriterion("ADDR <>", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThan(String value) {
            addCriterion("ADDR >", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ADDR >=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThan(String value) {
            addCriterion("ADDR <", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThanOrEqualTo(String value) {
            addCriterion("ADDR <=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLike(String value) {
            addCriterion("ADDR like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotLike(String value) {
            addCriterion("ADDR not like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrIn(List<String> values) {
            addCriterion("ADDR in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotIn(List<String> values) {
            addCriterion("ADDR not in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrBetween(String value1, String value2) {
            addCriterion("ADDR between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotBetween(String value1, String value2) {
            addCriterion("ADDR not between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrIsNull() {
            addCriterion("DETL_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andDetlAddrIsNotNull() {
            addCriterion("DETL_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andDetlAddrEqualTo(String value) {
            addCriterion("DETL_ADDR =", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrNotEqualTo(String value) {
            addCriterion("DETL_ADDR <>", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrGreaterThan(String value) {
            addCriterion("DETL_ADDR >", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrGreaterThanOrEqualTo(String value) {
            addCriterion("DETL_ADDR >=", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrLessThan(String value) {
            addCriterion("DETL_ADDR <", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrLessThanOrEqualTo(String value) {
            addCriterion("DETL_ADDR <=", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrLike(String value) {
            addCriterion("DETL_ADDR like", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrNotLike(String value) {
            addCriterion("DETL_ADDR not like", value, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrIn(List<String> values) {
            addCriterion("DETL_ADDR in", values, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrNotIn(List<String> values) {
            addCriterion("DETL_ADDR not in", values, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrBetween(String value1, String value2) {
            addCriterion("DETL_ADDR between", value1, value2, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andDetlAddrNotBetween(String value1, String value2) {
            addCriterion("DETL_ADDR not between", value1, value2, "detlAddr");
            return (Criteria) this;
        }

        public Criteria andTelNumIsNull() {
            addCriterion("TEL_NUM is null");
            return (Criteria) this;
        }

        public Criteria andTelNumIsNotNull() {
            addCriterion("TEL_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andTelNumEqualTo(String value) {
            addCriterion("TEL_NUM =", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumNotEqualTo(String value) {
            addCriterion("TEL_NUM <>", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumGreaterThan(String value) {
            addCriterion("TEL_NUM >", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumGreaterThanOrEqualTo(String value) {
            addCriterion("TEL_NUM >=", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumLessThan(String value) {
            addCriterion("TEL_NUM <", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumLessThanOrEqualTo(String value) {
            addCriterion("TEL_NUM <=", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumLike(String value) {
            addCriterion("TEL_NUM like", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumNotLike(String value) {
            addCriterion("TEL_NUM not like", value, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumIn(List<String> values) {
            addCriterion("TEL_NUM in", values, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumNotIn(List<String> values) {
            addCriterion("TEL_NUM not in", values, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumBetween(String value1, String value2) {
            addCriterion("TEL_NUM between", value1, value2, "telNum");
            return (Criteria) this;
        }

        public Criteria andTelNumNotBetween(String value1, String value2) {
            addCriterion("TEL_NUM not between", value1, value2, "telNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumIsNull() {
            addCriterion("MOBI_NUM is null");
            return (Criteria) this;
        }

        public Criteria andMobiNumIsNotNull() {
            addCriterion("MOBI_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andMobiNumEqualTo(String value) {
            addCriterion("MOBI_NUM =", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumNotEqualTo(String value) {
            addCriterion("MOBI_NUM <>", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumGreaterThan(String value) {
            addCriterion("MOBI_NUM >", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumGreaterThanOrEqualTo(String value) {
            addCriterion("MOBI_NUM >=", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumLessThan(String value) {
            addCriterion("MOBI_NUM <", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumLessThanOrEqualTo(String value) {
            addCriterion("MOBI_NUM <=", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumLike(String value) {
            addCriterion("MOBI_NUM like", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumNotLike(String value) {
            addCriterion("MOBI_NUM not like", value, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumIn(List<String> values) {
            addCriterion("MOBI_NUM in", values, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumNotIn(List<String> values) {
            addCriterion("MOBI_NUM not in", values, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumBetween(String value1, String value2) {
            addCriterion("MOBI_NUM between", value1, value2, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andMobiNumNotBetween(String value1, String value2) {
            addCriterion("MOBI_NUM not between", value1, value2, "mobiNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumIsNull() {
            addCriterion("FAX_NUM is null");
            return (Criteria) this;
        }

        public Criteria andFaxNumIsNotNull() {
            addCriterion("FAX_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andFaxNumEqualTo(String value) {
            addCriterion("FAX_NUM =", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumNotEqualTo(String value) {
            addCriterion("FAX_NUM <>", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumGreaterThan(String value) {
            addCriterion("FAX_NUM >", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumGreaterThanOrEqualTo(String value) {
            addCriterion("FAX_NUM >=", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumLessThan(String value) {
            addCriterion("FAX_NUM <", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumLessThanOrEqualTo(String value) {
            addCriterion("FAX_NUM <=", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumLike(String value) {
            addCriterion("FAX_NUM like", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumNotLike(String value) {
            addCriterion("FAX_NUM not like", value, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumIn(List<String> values) {
            addCriterion("FAX_NUM in", values, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumNotIn(List<String> values) {
            addCriterion("FAX_NUM not in", values, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumBetween(String value1, String value2) {
            addCriterion("FAX_NUM between", value1, value2, "faxNum");
            return (Criteria) this;
        }

        public Criteria andFaxNumNotBetween(String value1, String value2) {
            addCriterion("FAX_NUM not between", value1, value2, "faxNum");
            return (Criteria) this;
        }

        public Criteria andMailAddrIsNull() {
            addCriterion("MAIL_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andMailAddrIsNotNull() {
            addCriterion("MAIL_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andMailAddrEqualTo(String value) {
            addCriterion("MAIL_ADDR =", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotEqualTo(String value) {
            addCriterion("MAIL_ADDR <>", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrGreaterThan(String value) {
            addCriterion("MAIL_ADDR >", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrGreaterThanOrEqualTo(String value) {
            addCriterion("MAIL_ADDR >=", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrLessThan(String value) {
            addCriterion("MAIL_ADDR <", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrLessThanOrEqualTo(String value) {
            addCriterion("MAIL_ADDR <=", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrLike(String value) {
            addCriterion("MAIL_ADDR like", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotLike(String value) {
            addCriterion("MAIL_ADDR not like", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrIn(List<String> values) {
            addCriterion("MAIL_ADDR in", values, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotIn(List<String> values) {
            addCriterion("MAIL_ADDR not in", values, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrBetween(String value1, String value2) {
            addCriterion("MAIL_ADDR between", value1, value2, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotBetween(String value1, String value2) {
            addCriterion("MAIL_ADDR not between", value1, value2, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andApplIdIsNull() {
            addCriterion("APPL_ID is null");
            return (Criteria) this;
        }

        public Criteria andApplIdIsNotNull() {
            addCriterion("APPL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApplIdEqualTo(String value) {
            addCriterion("APPL_ID =", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdNotEqualTo(String value) {
            addCriterion("APPL_ID <>", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdGreaterThan(String value) {
            addCriterion("APPL_ID >", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdGreaterThanOrEqualTo(String value) {
            addCriterion("APPL_ID >=", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdLessThan(String value) {
            addCriterion("APPL_ID <", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdLessThanOrEqualTo(String value) {
            addCriterion("APPL_ID <=", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdLike(String value) {
            addCriterion("APPL_ID like", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdNotLike(String value) {
            addCriterion("APPL_ID not like", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdIn(List<String> values) {
            addCriterion("APPL_ID in", values, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdNotIn(List<String> values) {
            addCriterion("APPL_ID not in", values, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdBetween(String value1, String value2) {
            addCriterion("APPL_ID between", value1, value2, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdNotBetween(String value1, String value2) {
            addCriterion("APPL_ID not between", value1, value2, "applId");
            return (Criteria) this;
        }

        public Criteria andApplDateIsNull() {
            addCriterion("APPL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andApplDateIsNotNull() {
            addCriterion("APPL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andApplDateEqualTo(Date value) {
            addCriterion("APPL_DATE =", value, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateNotEqualTo(Date value) {
            addCriterion("APPL_DATE <>", value, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateGreaterThan(Date value) {
            addCriterion("APPL_DATE >", value, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateGreaterThanOrEqualTo(Date value) {
            addCriterion("APPL_DATE >=", value, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateLessThan(Date value) {
            addCriterion("APPL_DATE <", value, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateLessThanOrEqualTo(Date value) {
            addCriterion("APPL_DATE <=", value, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateIn(List<Date> values) {
            addCriterion("APPL_DATE in", values, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateNotIn(List<Date> values) {
            addCriterion("APPL_DATE not in", values, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateBetween(Date value1, Date value2) {
            addCriterion("APPL_DATE between", value1, value2, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplDateNotBetween(Date value1, Date value2) {
            addCriterion("APPL_DATE not between", value1, value2, "applDate");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeIsNull() {
            addCriterion("APPL_STS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeIsNotNull() {
            addCriterion("APPL_STS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeEqualTo(String value) {
            addCriterion("APPL_STS_CODE =", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeNotEqualTo(String value) {
            addCriterion("APPL_STS_CODE <>", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeGreaterThan(String value) {
            addCriterion("APPL_STS_CODE >", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("APPL_STS_CODE >=", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeLessThan(String value) {
            addCriterion("APPL_STS_CODE <", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeLessThanOrEqualTo(String value) {
            addCriterion("APPL_STS_CODE <=", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeLike(String value) {
            addCriterion("APPL_STS_CODE like", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeNotLike(String value) {
            addCriterion("APPL_STS_CODE not like", value, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeIn(List<String> values) {
            addCriterion("APPL_STS_CODE in", values, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeNotIn(List<String> values) {
            addCriterion("APPL_STS_CODE not in", values, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeBetween(String value1, String value2) {
            addCriterion("APPL_STS_CODE between", value1, value2, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andApplStsCodeNotBetween(String value1, String value2) {
            addCriterion("APPL_STS_CODE not between", value1, value2, "applStsCode");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnIsNull() {
            addCriterion("PRIV_INFO_YN is null");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnIsNotNull() {
            addCriterion("PRIV_INFO_YN is not null");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnEqualTo(String value) {
            addCriterion("PRIV_INFO_YN =", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnNotEqualTo(String value) {
            addCriterion("PRIV_INFO_YN <>", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnGreaterThan(String value) {
            addCriterion("PRIV_INFO_YN >", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnGreaterThanOrEqualTo(String value) {
            addCriterion("PRIV_INFO_YN >=", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnLessThan(String value) {
            addCriterion("PRIV_INFO_YN <", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnLessThanOrEqualTo(String value) {
            addCriterion("PRIV_INFO_YN <=", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnLike(String value) {
            addCriterion("PRIV_INFO_YN like", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnNotLike(String value) {
            addCriterion("PRIV_INFO_YN not like", value, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnIn(List<String> values) {
            addCriterion("PRIV_INFO_YN in", values, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnNotIn(List<String> values) {
            addCriterion("PRIV_INFO_YN not in", values, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnBetween(String value1, String value2) {
            addCriterion("PRIV_INFO_YN between", value1, value2, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andPrivInfoYnNotBetween(String value1, String value2) {
            addCriterion("PRIV_INFO_YN not between", value1, value2, "privInfoYn");
            return (Criteria) this;
        }

        public Criteria andCreIdIsNull() {
            addCriterion("CRE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreIdIsNotNull() {
            addCriterion("CRE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreIdEqualTo(String value) {
            addCriterion("CRE_ID =", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotEqualTo(String value) {
            addCriterion("CRE_ID <>", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdGreaterThan(String value) {
            addCriterion("CRE_ID >", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdGreaterThanOrEqualTo(String value) {
            addCriterion("CRE_ID >=", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdLessThan(String value) {
            addCriterion("CRE_ID <", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdLessThanOrEqualTo(String value) {
            addCriterion("CRE_ID <=", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdLike(String value) {
            addCriterion("CRE_ID like", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotLike(String value) {
            addCriterion("CRE_ID not like", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdIn(List<String> values) {
            addCriterion("CRE_ID in", values, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotIn(List<String> values) {
            addCriterion("CRE_ID not in", values, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdBetween(String value1, String value2) {
            addCriterion("CRE_ID between", value1, value2, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotBetween(String value1, String value2) {
            addCriterion("CRE_ID not between", value1, value2, "creId");
            return (Criteria) this;
        }

        public Criteria andCreDateIsNull() {
            addCriterion("CRE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreDateIsNotNull() {
            addCriterion("CRE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreDateEqualTo(Date value) {
            addCriterion("CRE_DATE =", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotEqualTo(Date value) {
            addCriterion("CRE_DATE <>", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateGreaterThan(Date value) {
            addCriterion("CRE_DATE >", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CRE_DATE >=", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateLessThan(Date value) {
            addCriterion("CRE_DATE <", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateLessThanOrEqualTo(Date value) {
            addCriterion("CRE_DATE <=", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateIn(List<Date> values) {
            addCriterion("CRE_DATE in", values, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotIn(List<Date> values) {
            addCriterion("CRE_DATE not in", values, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateBetween(Date value1, Date value2) {
            addCriterion("CRE_DATE between", value1, value2, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotBetween(Date value1, Date value2) {
            addCriterion("CRE_DATE not between", value1, value2, "creDate");
            return (Criteria) this;
        }

        public Criteria andModIdIsNull() {
            addCriterion("MOD_ID is null");
            return (Criteria) this;
        }

        public Criteria andModIdIsNotNull() {
            addCriterion("MOD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModIdEqualTo(String value) {
            addCriterion("MOD_ID =", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotEqualTo(String value) {
            addCriterion("MOD_ID <>", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdGreaterThan(String value) {
            addCriterion("MOD_ID >", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdGreaterThanOrEqualTo(String value) {
            addCriterion("MOD_ID >=", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLessThan(String value) {
            addCriterion("MOD_ID <", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLessThanOrEqualTo(String value) {
            addCriterion("MOD_ID <=", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLike(String value) {
            addCriterion("MOD_ID like", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotLike(String value) {
            addCriterion("MOD_ID not like", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdIn(List<String> values) {
            addCriterion("MOD_ID in", values, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotIn(List<String> values) {
            addCriterion("MOD_ID not in", values, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdBetween(String value1, String value2) {
            addCriterion("MOD_ID between", value1, value2, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotBetween(String value1, String value2) {
            addCriterion("MOD_ID not between", value1, value2, "modId");
            return (Criteria) this;
        }

        public Criteria andModDateIsNull() {
            addCriterion("MOD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModDateIsNotNull() {
            addCriterion("MOD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModDateEqualTo(Date value) {
            addCriterion("MOD_DATE =", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateNotEqualTo(Date value) {
            addCriterion("MOD_DATE <>", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateGreaterThan(Date value) {
            addCriterion("MOD_DATE >", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DATE >=", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateLessThan(Date value) {
            addCriterion("MOD_DATE <", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DATE <=", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateIn(List<Date> values) {
            addCriterion("MOD_DATE in", values, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateNotIn(List<Date> values) {
            addCriterion("MOD_DATE not in", values, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateBetween(Date value1, Date value2) {
            addCriterion("MOD_DATE between", value1, value2, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DATE not between", value1, value2, "modDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APPL
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 12 20:12:04 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APPL
     *
     * @mbggenerated Fri Sep 12 20:12:04 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}