package com.apexsoft.ysprj.applicants.admission.domain;

import java.util.Date;

public class AdmissionCourseMajorLanguage extends AdmissionCourseMajorLanguageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.MDT_YN
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private String mdtYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.CAN_YN
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private String canYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.MIN_SCR
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private Integer minScr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.MSG_NO
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private String msgNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.CRE_ID
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.CRE_DATE
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.MOD_ID
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.MOD_DATE
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.MDT_YN
     *
     * @return the value of ADMS_CORS_MAJ_LANG.MDT_YN
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public String getMdtYn() {
        return mdtYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.MDT_YN
     *
     * @param mdtYn the value for ADMS_CORS_MAJ_LANG.MDT_YN
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setMdtYn(String mdtYn) {
        this.mdtYn = mdtYn == null ? null : mdtYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.CAN_YN
     *
     * @return the value of ADMS_CORS_MAJ_LANG.CAN_YN
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public String getCanYn() {
        return canYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.CAN_YN
     *
     * @param canYn the value for ADMS_CORS_MAJ_LANG.CAN_YN
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setCanYn(String canYn) {
        this.canYn = canYn == null ? null : canYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.MIN_SCR
     *
     * @return the value of ADMS_CORS_MAJ_LANG.MIN_SCR
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public Integer getMinScr() {
        return minScr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.MIN_SCR
     *
     * @param minScr the value for ADMS_CORS_MAJ_LANG.MIN_SCR
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setMinScr(Integer minScr) {
        this.minScr = minScr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.MSG_NO
     *
     * @return the value of ADMS_CORS_MAJ_LANG.MSG_NO
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public String getMsgNo() {
        return msgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.MSG_NO
     *
     * @param msgNo the value for ADMS_CORS_MAJ_LANG.MSG_NO
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setMsgNo(String msgNo) {
        this.msgNo = msgNo == null ? null : msgNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.CRE_ID
     *
     * @return the value of ADMS_CORS_MAJ_LANG.CRE_ID
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.CRE_ID
     *
     * @param creId the value for ADMS_CORS_MAJ_LANG.CRE_ID
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.CRE_DATE
     *
     * @return the value of ADMS_CORS_MAJ_LANG.CRE_DATE
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.CRE_DATE
     *
     * @param creDate the value for ADMS_CORS_MAJ_LANG.CRE_DATE
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.MOD_ID
     *
     * @return the value of ADMS_CORS_MAJ_LANG.MOD_ID
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.MOD_ID
     *
     * @param modId the value for ADMS_CORS_MAJ_LANG.MOD_ID
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.MOD_DATE
     *
     * @return the value of ADMS_CORS_MAJ_LANG.MOD_DATE
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.MOD_DATE
     *
     * @param modDate the value for ADMS_CORS_MAJ_LANG.MOD_DATE
     *
     * @mbggenerated Wed Sep 03 21:15:46 KST 2014
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}