package com.apexsoft.ysprj.applicants.admission.domain;

public class AdmissionCourseMajorLanguageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.ADMS_CORS_NO
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private Integer admsCorsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.DETL_MAJ_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private String detlMajCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.GRP_LEVEL
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private Integer grpLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.EXAM_CODE_GRP
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private String examCodeGrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_LANG.EXAM_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private String examCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.ADMS_CORS_NO
     *
     * @return the value of ADMS_CORS_MAJ_LANG.ADMS_CORS_NO
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public Integer getAdmsCorsNo() {
        return admsCorsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.ADMS_CORS_NO
     *
     * @param admsCorsNo the value for ADMS_CORS_MAJ_LANG.ADMS_CORS_NO
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setAdmsCorsNo(Integer admsCorsNo) {
        this.admsCorsNo = admsCorsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.DETL_MAJ_CODE
     *
     * @return the value of ADMS_CORS_MAJ_LANG.DETL_MAJ_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public String getDetlMajCode() {
        return detlMajCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.DETL_MAJ_CODE
     *
     * @param detlMajCode the value for ADMS_CORS_MAJ_LANG.DETL_MAJ_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setDetlMajCode(String detlMajCode) {
        this.detlMajCode = detlMajCode == null ? null : detlMajCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.GRP_LEVEL
     *
     * @return the value of ADMS_CORS_MAJ_LANG.GRP_LEVEL
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public Integer getGrpLevel() {
        return grpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.GRP_LEVEL
     *
     * @param grpLevel the value for ADMS_CORS_MAJ_LANG.GRP_LEVEL
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setGrpLevel(Integer grpLevel) {
        this.grpLevel = grpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.EXAM_CODE_GRP
     *
     * @return the value of ADMS_CORS_MAJ_LANG.EXAM_CODE_GRP
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public String getExamCodeGrp() {
        return examCodeGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.EXAM_CODE_GRP
     *
     * @param examCodeGrp the value for ADMS_CORS_MAJ_LANG.EXAM_CODE_GRP
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setExamCodeGrp(String examCodeGrp) {
        this.examCodeGrp = examCodeGrp == null ? null : examCodeGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_LANG.EXAM_CODE
     *
     * @return the value of ADMS_CORS_MAJ_LANG.EXAM_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public String getExamCode() {
        return examCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_LANG.EXAM_CODE
     *
     * @param examCode the value for ADMS_CORS_MAJ_LANG.EXAM_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setExamCode(String examCode) {
        this.examCode = examCode == null ? null : examCode.trim();
    }
}