package com.apexsoft.ysprj.applicants.admission.domain;

public class AdmissionDepartmentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_DEPT.ADMS_NO
     *
     * @mbggenerated Sun Sep 14 20:44:39 KST 2014
     */
    private String admsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_DEPT.DEPT_CODE
     *
     * @mbggenerated Sun Sep 14 20:44:39 KST 2014
     */
    private String deptCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_DEPT.ADMS_NO
     *
     * @return the value of ADMS_DEPT.ADMS_NO
     *
     * @mbggenerated Sun Sep 14 20:44:39 KST 2014
     */
    public String getAdmsNo() {
        return admsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_DEPT.ADMS_NO
     *
     * @param admsNo the value for ADMS_DEPT.ADMS_NO
     *
     * @mbggenerated Sun Sep 14 20:44:39 KST 2014
     */
    public void setAdmsNo(String admsNo) {
        this.admsNo = admsNo == null ? null : admsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_DEPT.DEPT_CODE
     *
     * @return the value of ADMS_DEPT.DEPT_CODE
     *
     * @mbggenerated Sun Sep 14 20:44:39 KST 2014
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_DEPT.DEPT_CODE
     *
     * @param deptCode the value for ADMS_DEPT.DEPT_CODE
     *
     * @mbggenerated Sun Sep 14 20:44:39 KST 2014
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }
}