package com.apexsoft.ysprj.applicants.admission.domain;

public class AdmissionCourseMajorMandatoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_MDT.ADMS_CORS_NO
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private Integer admsCorsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_MDT.DETL_MAJ_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private String detlMajCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_MDT.GRP_LEVEL
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private Integer grpLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_MDT.DOC_ITEM_GRP
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private String docItemGrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_MDT.DOC_ITEM_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private String docItemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMS_CORS_MAJ_MDT.DOC_TYPE_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    private String docTypeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_MDT.ADMS_CORS_NO
     *
     * @return the value of ADMS_CORS_MAJ_MDT.ADMS_CORS_NO
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public Integer getAdmsCorsNo() {
        return admsCorsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_MDT.ADMS_CORS_NO
     *
     * @param admsCorsNo the value for ADMS_CORS_MAJ_MDT.ADMS_CORS_NO
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setAdmsCorsNo(Integer admsCorsNo) {
        this.admsCorsNo = admsCorsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_MDT.DETL_MAJ_CODE
     *
     * @return the value of ADMS_CORS_MAJ_MDT.DETL_MAJ_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public String getDetlMajCode() {
        return detlMajCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_MDT.DETL_MAJ_CODE
     *
     * @param detlMajCode the value for ADMS_CORS_MAJ_MDT.DETL_MAJ_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setDetlMajCode(String detlMajCode) {
        this.detlMajCode = detlMajCode == null ? null : detlMajCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_MDT.GRP_LEVEL
     *
     * @return the value of ADMS_CORS_MAJ_MDT.GRP_LEVEL
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public Integer getGrpLevel() {
        return grpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_MDT.GRP_LEVEL
     *
     * @param grpLevel the value for ADMS_CORS_MAJ_MDT.GRP_LEVEL
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setGrpLevel(Integer grpLevel) {
        this.grpLevel = grpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_MDT.DOC_ITEM_GRP
     *
     * @return the value of ADMS_CORS_MAJ_MDT.DOC_ITEM_GRP
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public String getDocItemGrp() {
        return docItemGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_MDT.DOC_ITEM_GRP
     *
     * @param docItemGrp the value for ADMS_CORS_MAJ_MDT.DOC_ITEM_GRP
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setDocItemGrp(String docItemGrp) {
        this.docItemGrp = docItemGrp == null ? null : docItemGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_MDT.DOC_ITEM_CODE
     *
     * @return the value of ADMS_CORS_MAJ_MDT.DOC_ITEM_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public String getDocItemCode() {
        return docItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_MDT.DOC_ITEM_CODE
     *
     * @param docItemCode the value for ADMS_CORS_MAJ_MDT.DOC_ITEM_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setDocItemCode(String docItemCode) {
        this.docItemCode = docItemCode == null ? null : docItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMS_CORS_MAJ_MDT.DOC_TYPE_CODE
     *
     * @return the value of ADMS_CORS_MAJ_MDT.DOC_TYPE_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public String getDocTypeCode() {
        return docTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMS_CORS_MAJ_MDT.DOC_TYPE_CODE
     *
     * @param docTypeCode the value for ADMS_CORS_MAJ_MDT.DOC_TYPE_CODE
     *
     * @mbggenerated Wed Jan 28 17:22:25 KST 2015
     */
    public void setDocTypeCode(String docTypeCode) {
        this.docTypeCode = docTypeCode == null ? null : docTypeCode.trim();
    }
}