package com.apexsoft.ysprj.admin.domain;

import java.util.Date;

public class ApplicationCheck extends ApplicationCheckKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.CHK_CODE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private String chkCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.CHK_YN
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private String chkYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.CHK_DAY
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private String chkDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.CHK_USER_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private String chkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.CRE_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.CRE_DATE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.MOD_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHK.MOD_DATE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.CHK_CODE
     *
     * @return the value of APPL_CHK.CHK_CODE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public String getChkCode() {
        return chkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.CHK_CODE
     *
     * @param chkCode the value for APPL_CHK.CHK_CODE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setChkCode(String chkCode) {
        this.chkCode = chkCode == null ? null : chkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.CHK_YN
     *
     * @return the value of APPL_CHK.CHK_YN
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public String getChkYn() {
        return chkYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.CHK_YN
     *
     * @param chkYn the value for APPL_CHK.CHK_YN
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setChkYn(String chkYn) {
        this.chkYn = chkYn == null ? null : chkYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.CHK_DAY
     *
     * @return the value of APPL_CHK.CHK_DAY
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public String getChkDay() {
        return chkDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.CHK_DAY
     *
     * @param chkDay the value for APPL_CHK.CHK_DAY
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setChkDay(String chkDay) {
        this.chkDay = chkDay == null ? null : chkDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.CHK_USER_ID
     *
     * @return the value of APPL_CHK.CHK_USER_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public String getChkUserId() {
        return chkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.CHK_USER_ID
     *
     * @param chkUserId the value for APPL_CHK.CHK_USER_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setChkUserId(String chkUserId) {
        this.chkUserId = chkUserId == null ? null : chkUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.CRE_ID
     *
     * @return the value of APPL_CHK.CRE_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.CRE_ID
     *
     * @param creId the value for APPL_CHK.CRE_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.CRE_DATE
     *
     * @return the value of APPL_CHK.CRE_DATE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.CRE_DATE
     *
     * @param creDate the value for APPL_CHK.CRE_DATE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.MOD_ID
     *
     * @return the value of APPL_CHK.MOD_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.MOD_ID
     *
     * @param modId the value for APPL_CHK.MOD_ID
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHK.MOD_DATE
     *
     * @return the value of APPL_CHK.MOD_DATE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHK.MOD_DATE
     *
     * @param modDate the value for APPL_CHK.MOD_DATE
     *
     * @mbggenerated Tue Apr 07 17:27:42 KST 2015
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}