package com.apexsoft.ysprj.admin.domain;

import java.util.Date;

public class ApplicationChange extends ApplicationChangeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.APPL_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private Integer applNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.APPL_CHG_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String applChgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.CHG_STS_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String chgStsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.REQ_DAY
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String reqDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.REQ_USER_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String reqUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.REQ_NAME
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String reqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.ACT_DAY
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String actDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.ACT_USER_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String actUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_ADMS_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String befAdmsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_DEPT_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String befDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_ARI_INST_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String befAriInstCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_CORS_TYPE_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String befCorsTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_DETL_MAJ_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String befDetlMajCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_APPL_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String befApplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_ADMS_FEE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private Integer befAdmsFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_ADMS_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String aftAdmsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_DEPT_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String aftDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_ARI_INST_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String aftAriInstCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_CORS_TYPE_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String aftCorsTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_DETL_MAJ_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String aftDetlMajCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_APPL_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String aftApplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_ADMS_FEE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private Integer aftAdmsFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.PAY_STS
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String paySts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.CHG_COLM
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String chgColm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.CHG_COLM_NAME
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String chgColmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.BEF_VAL
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String befVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.AFT_VAL
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String aftVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.CNCL_RESN
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String cnclResn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.CRE_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.CRE_DATE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.MOD_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPL_CHG.MOD_DATE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.APPL_NO
     *
     * @return the value of APPL_CHG.APPL_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public Integer getApplNo() {
        return applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.APPL_NO
     *
     * @param applNo the value for APPL_CHG.APPL_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setApplNo(Integer applNo) {
        this.applNo = applNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.APPL_CHG_CODE
     *
     * @return the value of APPL_CHG.APPL_CHG_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getApplChgCode() {
        return applChgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.APPL_CHG_CODE
     *
     * @param applChgCode the value for APPL_CHG.APPL_CHG_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setApplChgCode(String applChgCode) {
        this.applChgCode = applChgCode == null ? null : applChgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.CHG_STS_CODE
     *
     * @return the value of APPL_CHG.CHG_STS_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getChgStsCode() {
        return chgStsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.CHG_STS_CODE
     *
     * @param chgStsCode the value for APPL_CHG.CHG_STS_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setChgStsCode(String chgStsCode) {
        this.chgStsCode = chgStsCode == null ? null : chgStsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.REQ_DAY
     *
     * @return the value of APPL_CHG.REQ_DAY
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getReqDay() {
        return reqDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.REQ_DAY
     *
     * @param reqDay the value for APPL_CHG.REQ_DAY
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setReqDay(String reqDay) {
        this.reqDay = reqDay == null ? null : reqDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.REQ_USER_ID
     *
     * @return the value of APPL_CHG.REQ_USER_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getReqUserId() {
        return reqUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.REQ_USER_ID
     *
     * @param reqUserId the value for APPL_CHG.REQ_USER_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setReqUserId(String reqUserId) {
        this.reqUserId = reqUserId == null ? null : reqUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.REQ_NAME
     *
     * @return the value of APPL_CHG.REQ_NAME
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getReqName() {
        return reqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.REQ_NAME
     *
     * @param reqName the value for APPL_CHG.REQ_NAME
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setReqName(String reqName) {
        this.reqName = reqName == null ? null : reqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.ACT_DAY
     *
     * @return the value of APPL_CHG.ACT_DAY
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getActDay() {
        return actDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.ACT_DAY
     *
     * @param actDay the value for APPL_CHG.ACT_DAY
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setActDay(String actDay) {
        this.actDay = actDay == null ? null : actDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.ACT_USER_ID
     *
     * @return the value of APPL_CHG.ACT_USER_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getActUserId() {
        return actUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.ACT_USER_ID
     *
     * @param actUserId the value for APPL_CHG.ACT_USER_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setActUserId(String actUserId) {
        this.actUserId = actUserId == null ? null : actUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_ADMS_NO
     *
     * @return the value of APPL_CHG.BEF_ADMS_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getBefAdmsNo() {
        return befAdmsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_ADMS_NO
     *
     * @param befAdmsNo the value for APPL_CHG.BEF_ADMS_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefAdmsNo(String befAdmsNo) {
        this.befAdmsNo = befAdmsNo == null ? null : befAdmsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_DEPT_CODE
     *
     * @return the value of APPL_CHG.BEF_DEPT_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getBefDeptCode() {
        return befDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_DEPT_CODE
     *
     * @param befDeptCode the value for APPL_CHG.BEF_DEPT_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefDeptCode(String befDeptCode) {
        this.befDeptCode = befDeptCode == null ? null : befDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_ARI_INST_CODE
     *
     * @return the value of APPL_CHG.BEF_ARI_INST_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getBefAriInstCode() {
        return befAriInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_ARI_INST_CODE
     *
     * @param befAriInstCode the value for APPL_CHG.BEF_ARI_INST_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefAriInstCode(String befAriInstCode) {
        this.befAriInstCode = befAriInstCode == null ? null : befAriInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_CORS_TYPE_CODE
     *
     * @return the value of APPL_CHG.BEF_CORS_TYPE_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getBefCorsTypeCode() {
        return befCorsTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_CORS_TYPE_CODE
     *
     * @param befCorsTypeCode the value for APPL_CHG.BEF_CORS_TYPE_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefCorsTypeCode(String befCorsTypeCode) {
        this.befCorsTypeCode = befCorsTypeCode == null ? null : befCorsTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_DETL_MAJ_CODE
     *
     * @return the value of APPL_CHG.BEF_DETL_MAJ_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getBefDetlMajCode() {
        return befDetlMajCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_DETL_MAJ_CODE
     *
     * @param befDetlMajCode the value for APPL_CHG.BEF_DETL_MAJ_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefDetlMajCode(String befDetlMajCode) {
        this.befDetlMajCode = befDetlMajCode == null ? null : befDetlMajCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_APPL_ID
     *
     * @return the value of APPL_CHG.BEF_APPL_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getBefApplId() {
        return befApplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_APPL_ID
     *
     * @param befApplId the value for APPL_CHG.BEF_APPL_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefApplId(String befApplId) {
        this.befApplId = befApplId == null ? null : befApplId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_ADMS_FEE
     *
     * @return the value of APPL_CHG.BEF_ADMS_FEE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public Integer getBefAdmsFee() {
        return befAdmsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_ADMS_FEE
     *
     * @param befAdmsFee the value for APPL_CHG.BEF_ADMS_FEE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefAdmsFee(Integer befAdmsFee) {
        this.befAdmsFee = befAdmsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_ADMS_NO
     *
     * @return the value of APPL_CHG.AFT_ADMS_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getAftAdmsNo() {
        return aftAdmsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_ADMS_NO
     *
     * @param aftAdmsNo the value for APPL_CHG.AFT_ADMS_NO
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftAdmsNo(String aftAdmsNo) {
        this.aftAdmsNo = aftAdmsNo == null ? null : aftAdmsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_DEPT_CODE
     *
     * @return the value of APPL_CHG.AFT_DEPT_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getAftDeptCode() {
        return aftDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_DEPT_CODE
     *
     * @param aftDeptCode the value for APPL_CHG.AFT_DEPT_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftDeptCode(String aftDeptCode) {
        this.aftDeptCode = aftDeptCode == null ? null : aftDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_ARI_INST_CODE
     *
     * @return the value of APPL_CHG.AFT_ARI_INST_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getAftAriInstCode() {
        return aftAriInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_ARI_INST_CODE
     *
     * @param aftAriInstCode the value for APPL_CHG.AFT_ARI_INST_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftAriInstCode(String aftAriInstCode) {
        this.aftAriInstCode = aftAriInstCode == null ? null : aftAriInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_CORS_TYPE_CODE
     *
     * @return the value of APPL_CHG.AFT_CORS_TYPE_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getAftCorsTypeCode() {
        return aftCorsTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_CORS_TYPE_CODE
     *
     * @param aftCorsTypeCode the value for APPL_CHG.AFT_CORS_TYPE_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftCorsTypeCode(String aftCorsTypeCode) {
        this.aftCorsTypeCode = aftCorsTypeCode == null ? null : aftCorsTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_DETL_MAJ_CODE
     *
     * @return the value of APPL_CHG.AFT_DETL_MAJ_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getAftDetlMajCode() {
        return aftDetlMajCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_DETL_MAJ_CODE
     *
     * @param aftDetlMajCode the value for APPL_CHG.AFT_DETL_MAJ_CODE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftDetlMajCode(String aftDetlMajCode) {
        this.aftDetlMajCode = aftDetlMajCode == null ? null : aftDetlMajCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_APPL_ID
     *
     * @return the value of APPL_CHG.AFT_APPL_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getAftApplId() {
        return aftApplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_APPL_ID
     *
     * @param aftApplId the value for APPL_CHG.AFT_APPL_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftApplId(String aftApplId) {
        this.aftApplId = aftApplId == null ? null : aftApplId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_ADMS_FEE
     *
     * @return the value of APPL_CHG.AFT_ADMS_FEE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public Integer getAftAdmsFee() {
        return aftAdmsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_ADMS_FEE
     *
     * @param aftAdmsFee the value for APPL_CHG.AFT_ADMS_FEE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftAdmsFee(Integer aftAdmsFee) {
        this.aftAdmsFee = aftAdmsFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.PAY_STS
     *
     * @return the value of APPL_CHG.PAY_STS
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getPaySts() {
        return paySts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.PAY_STS
     *
     * @param paySts the value for APPL_CHG.PAY_STS
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setPaySts(String paySts) {
        this.paySts = paySts == null ? null : paySts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.CHG_COLM
     *
     * @return the value of APPL_CHG.CHG_COLM
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getChgColm() {
        return chgColm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.CHG_COLM
     *
     * @param chgColm the value for APPL_CHG.CHG_COLM
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setChgColm(String chgColm) {
        this.chgColm = chgColm == null ? null : chgColm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.CHG_COLM_NAME
     *
     * @return the value of APPL_CHG.CHG_COLM_NAME
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getChgColmName() {
        return chgColmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.CHG_COLM_NAME
     *
     * @param chgColmName the value for APPL_CHG.CHG_COLM_NAME
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setChgColmName(String chgColmName) {
        this.chgColmName = chgColmName == null ? null : chgColmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.BEF_VAL
     *
     * @return the value of APPL_CHG.BEF_VAL
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getBefVal() {
        return befVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.BEF_VAL
     *
     * @param befVal the value for APPL_CHG.BEF_VAL
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setBefVal(String befVal) {
        this.befVal = befVal == null ? null : befVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.AFT_VAL
     *
     * @return the value of APPL_CHG.AFT_VAL
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getAftVal() {
        return aftVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.AFT_VAL
     *
     * @param aftVal the value for APPL_CHG.AFT_VAL
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setAftVal(String aftVal) {
        this.aftVal = aftVal == null ? null : aftVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.CNCL_RESN
     *
     * @return the value of APPL_CHG.CNCL_RESN
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getCnclResn() {
        return cnclResn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.CNCL_RESN
     *
     * @param cnclResn the value for APPL_CHG.CNCL_RESN
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setCnclResn(String cnclResn) {
        this.cnclResn = cnclResn == null ? null : cnclResn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.CRE_ID
     *
     * @return the value of APPL_CHG.CRE_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.CRE_ID
     *
     * @param creId the value for APPL_CHG.CRE_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.CRE_DATE
     *
     * @return the value of APPL_CHG.CRE_DATE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.CRE_DATE
     *
     * @param creDate the value for APPL_CHG.CRE_DATE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.MOD_ID
     *
     * @return the value of APPL_CHG.MOD_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.MOD_ID
     *
     * @param modId the value for APPL_CHG.MOD_ID
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPL_CHG.MOD_DATE
     *
     * @return the value of APPL_CHG.MOD_DATE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPL_CHG.MOD_DATE
     *
     * @param modDate the value for APPL_CHG.MOD_DATE
     *
     * @mbggenerated Wed Feb 11 11:38:55 KST 2015
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}