package com.apexsoft.ysprj.admin.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MandatoryAdmissionCourseMajorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public MandatoryAdmissionCourseMajorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdmsCorsNoIsNull() {
            addCriterion("ADMS_CORS_NO is null");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoIsNotNull() {
            addCriterion("ADMS_CORS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoEqualTo(Integer value) {
            addCriterion("ADMS_CORS_NO =", value, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoNotEqualTo(Integer value) {
            addCriterion("ADMS_CORS_NO <>", value, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoGreaterThan(Integer value) {
            addCriterion("ADMS_CORS_NO >", value, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ADMS_CORS_NO >=", value, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoLessThan(Integer value) {
            addCriterion("ADMS_CORS_NO <", value, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoLessThanOrEqualTo(Integer value) {
            addCriterion("ADMS_CORS_NO <=", value, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoIn(List<Integer> values) {
            addCriterion("ADMS_CORS_NO in", values, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoNotIn(List<Integer> values) {
            addCriterion("ADMS_CORS_NO not in", values, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoBetween(Integer value1, Integer value2) {
            addCriterion("ADMS_CORS_NO between", value1, value2, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andAdmsCorsNoNotBetween(Integer value1, Integer value2) {
            addCriterion("ADMS_CORS_NO not between", value1, value2, "admsCorsNo");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeIsNull() {
            addCriterion("DETL_MAJ_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeIsNotNull() {
            addCriterion("DETL_MAJ_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE =", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE <>", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeGreaterThan(String value) {
            addCriterion("DETL_MAJ_CODE >", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE >=", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeLessThan(String value) {
            addCriterion("DETL_MAJ_CODE <", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeLessThanOrEqualTo(String value) {
            addCriterion("DETL_MAJ_CODE <=", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeLike(String value) {
            addCriterion("DETL_MAJ_CODE like", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotLike(String value) {
            addCriterion("DETL_MAJ_CODE not like", value, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeIn(List<String> values) {
            addCriterion("DETL_MAJ_CODE in", values, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotIn(List<String> values) {
            addCriterion("DETL_MAJ_CODE not in", values, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeBetween(String value1, String value2) {
            addCriterion("DETL_MAJ_CODE between", value1, value2, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andDetlMajCodeNotBetween(String value1, String value2) {
            addCriterion("DETL_MAJ_CODE not between", value1, value2, "detlMajCode");
            return (Criteria) this;
        }

        public Criteria andGrpLevelIsNull() {
            addCriterion("GRP_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andGrpLevelIsNotNull() {
            addCriterion("GRP_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andGrpLevelEqualTo(Integer value) {
            addCriterion("GRP_LEVEL =", value, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelNotEqualTo(Integer value) {
            addCriterion("GRP_LEVEL <>", value, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelGreaterThan(Integer value) {
            addCriterion("GRP_LEVEL >", value, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("GRP_LEVEL >=", value, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelLessThan(Integer value) {
            addCriterion("GRP_LEVEL <", value, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelLessThanOrEqualTo(Integer value) {
            addCriterion("GRP_LEVEL <=", value, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelIn(List<Integer> values) {
            addCriterion("GRP_LEVEL in", values, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelNotIn(List<Integer> values) {
            addCriterion("GRP_LEVEL not in", values, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelBetween(Integer value1, Integer value2) {
            addCriterion("GRP_LEVEL between", value1, value2, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andGrpLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("GRP_LEVEL not between", value1, value2, "grpLevel");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpIsNull() {
            addCriterion("ITEM_CODE_GRP is null");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpIsNotNull() {
            addCriterion("ITEM_CODE_GRP is not null");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpEqualTo(String value) {
            addCriterion("ITEM_CODE_GRP =", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpNotEqualTo(String value) {
            addCriterion("ITEM_CODE_GRP <>", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpGreaterThan(String value) {
            addCriterion("ITEM_CODE_GRP >", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpGreaterThanOrEqualTo(String value) {
            addCriterion("ITEM_CODE_GRP >=", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpLessThan(String value) {
            addCriterion("ITEM_CODE_GRP <", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpLessThanOrEqualTo(String value) {
            addCriterion("ITEM_CODE_GRP <=", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpLike(String value) {
            addCriterion("ITEM_CODE_GRP like", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpNotLike(String value) {
            addCriterion("ITEM_CODE_GRP not like", value, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpIn(List<String> values) {
            addCriterion("ITEM_CODE_GRP in", values, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpNotIn(List<String> values) {
            addCriterion("ITEM_CODE_GRP not in", values, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpBetween(String value1, String value2) {
            addCriterion("ITEM_CODE_GRP between", value1, value2, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeGrpNotBetween(String value1, String value2) {
            addCriterion("ITEM_CODE_GRP not between", value1, value2, "itemCodeGrp");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNull() {
            addCriterion("ITEM_CODE is null");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNotNull() {
            addCriterion("ITEM_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andItemCodeEqualTo(String value) {
            addCriterion("ITEM_CODE =", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotEqualTo(String value) {
            addCriterion("ITEM_CODE <>", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThan(String value) {
            addCriterion("ITEM_CODE >", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ITEM_CODE >=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThan(String value) {
            addCriterion("ITEM_CODE <", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThanOrEqualTo(String value) {
            addCriterion("ITEM_CODE <=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLike(String value) {
            addCriterion("ITEM_CODE like", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotLike(String value) {
            addCriterion("ITEM_CODE not like", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeIn(List<String> values) {
            addCriterion("ITEM_CODE in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotIn(List<String> values) {
            addCriterion("ITEM_CODE not in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeBetween(String value1, String value2) {
            addCriterion("ITEM_CODE between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotBetween(String value1, String value2) {
            addCriterion("ITEM_CODE not between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpIsNull() {
            addCriterion("UP_CODE_GRP is null");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpIsNotNull() {
            addCriterion("UP_CODE_GRP is not null");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpEqualTo(String value) {
            addCriterion("UP_CODE_GRP =", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpNotEqualTo(String value) {
            addCriterion("UP_CODE_GRP <>", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpGreaterThan(String value) {
            addCriterion("UP_CODE_GRP >", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpGreaterThanOrEqualTo(String value) {
            addCriterion("UP_CODE_GRP >=", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpLessThan(String value) {
            addCriterion("UP_CODE_GRP <", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpLessThanOrEqualTo(String value) {
            addCriterion("UP_CODE_GRP <=", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpLike(String value) {
            addCriterion("UP_CODE_GRP like", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpNotLike(String value) {
            addCriterion("UP_CODE_GRP not like", value, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpIn(List<String> values) {
            addCriterion("UP_CODE_GRP in", values, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpNotIn(List<String> values) {
            addCriterion("UP_CODE_GRP not in", values, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpBetween(String value1, String value2) {
            addCriterion("UP_CODE_GRP between", value1, value2, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeGrpNotBetween(String value1, String value2) {
            addCriterion("UP_CODE_GRP not between", value1, value2, "upCodeGrp");
            return (Criteria) this;
        }

        public Criteria andUpCodeIsNull() {
            addCriterion("UP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUpCodeIsNotNull() {
            addCriterion("UP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUpCodeEqualTo(String value) {
            addCriterion("UP_CODE =", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeNotEqualTo(String value) {
            addCriterion("UP_CODE <>", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeGreaterThan(String value) {
            addCriterion("UP_CODE >", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UP_CODE >=", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeLessThan(String value) {
            addCriterion("UP_CODE <", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeLessThanOrEqualTo(String value) {
            addCriterion("UP_CODE <=", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeLike(String value) {
            addCriterion("UP_CODE like", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeNotLike(String value) {
            addCriterion("UP_CODE not like", value, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeIn(List<String> values) {
            addCriterion("UP_CODE in", values, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeNotIn(List<String> values) {
            addCriterion("UP_CODE not in", values, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeBetween(String value1, String value2) {
            addCriterion("UP_CODE between", value1, value2, "upCode");
            return (Criteria) this;
        }

        public Criteria andUpCodeNotBetween(String value1, String value2) {
            addCriterion("UP_CODE not between", value1, value2, "upCode");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpIsNull() {
            addCriterion("SEL_CODE_GRP is null");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpIsNotNull() {
            addCriterion("SEL_CODE_GRP is not null");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpEqualTo(String value) {
            addCriterion("SEL_CODE_GRP =", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpNotEqualTo(String value) {
            addCriterion("SEL_CODE_GRP <>", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpGreaterThan(String value) {
            addCriterion("SEL_CODE_GRP >", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpGreaterThanOrEqualTo(String value) {
            addCriterion("SEL_CODE_GRP >=", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpLessThan(String value) {
            addCriterion("SEL_CODE_GRP <", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpLessThanOrEqualTo(String value) {
            addCriterion("SEL_CODE_GRP <=", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpLike(String value) {
            addCriterion("SEL_CODE_GRP like", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpNotLike(String value) {
            addCriterion("SEL_CODE_GRP not like", value, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpIn(List<String> values) {
            addCriterion("SEL_CODE_GRP in", values, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpNotIn(List<String> values) {
            addCriterion("SEL_CODE_GRP not in", values, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpBetween(String value1, String value2) {
            addCriterion("SEL_CODE_GRP between", value1, value2, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andSelCodeGrpNotBetween(String value1, String value2) {
            addCriterion("SEL_CODE_GRP not between", value1, value2, "selCodeGrp");
            return (Criteria) this;
        }

        public Criteria andChnYnIsNull() {
            addCriterion("CHN_YN is null");
            return (Criteria) this;
        }

        public Criteria andChnYnIsNotNull() {
            addCriterion("CHN_YN is not null");
            return (Criteria) this;
        }

        public Criteria andChnYnEqualTo(String value) {
            addCriterion("CHN_YN =", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnNotEqualTo(String value) {
            addCriterion("CHN_YN <>", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnGreaterThan(String value) {
            addCriterion("CHN_YN >", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnGreaterThanOrEqualTo(String value) {
            addCriterion("CHN_YN >=", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnLessThan(String value) {
            addCriterion("CHN_YN <", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnLessThanOrEqualTo(String value) {
            addCriterion("CHN_YN <=", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnLike(String value) {
            addCriterion("CHN_YN like", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnNotLike(String value) {
            addCriterion("CHN_YN not like", value, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnIn(List<String> values) {
            addCriterion("CHN_YN in", values, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnNotIn(List<String> values) {
            addCriterion("CHN_YN not in", values, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnBetween(String value1, String value2) {
            addCriterion("CHN_YN between", value1, value2, "chnYn");
            return (Criteria) this;
        }

        public Criteria andChnYnNotBetween(String value1, String value2) {
            addCriterion("CHN_YN not between", value1, value2, "chnYn");
            return (Criteria) this;
        }

        public Criteria andLastYnIsNull() {
            addCriterion("LAST_YN is null");
            return (Criteria) this;
        }

        public Criteria andLastYnIsNotNull() {
            addCriterion("LAST_YN is not null");
            return (Criteria) this;
        }

        public Criteria andLastYnEqualTo(String value) {
            addCriterion("LAST_YN =", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnNotEqualTo(String value) {
            addCriterion("LAST_YN <>", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnGreaterThan(String value) {
            addCriterion("LAST_YN >", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_YN >=", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnLessThan(String value) {
            addCriterion("LAST_YN <", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnLessThanOrEqualTo(String value) {
            addCriterion("LAST_YN <=", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnLike(String value) {
            addCriterion("LAST_YN like", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnNotLike(String value) {
            addCriterion("LAST_YN not like", value, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnIn(List<String> values) {
            addCriterion("LAST_YN in", values, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnNotIn(List<String> values) {
            addCriterion("LAST_YN not in", values, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnBetween(String value1, String value2) {
            addCriterion("LAST_YN between", value1, value2, "lastYn");
            return (Criteria) this;
        }

        public Criteria andLastYnNotBetween(String value1, String value2) {
            addCriterion("LAST_YN not between", value1, value2, "lastYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnIsNull() {
            addCriterion("MDT_YN is null");
            return (Criteria) this;
        }

        public Criteria andMdtYnIsNotNull() {
            addCriterion("MDT_YN is not null");
            return (Criteria) this;
        }

        public Criteria andMdtYnEqualTo(String value) {
            addCriterion("MDT_YN =", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnNotEqualTo(String value) {
            addCriterion("MDT_YN <>", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnGreaterThan(String value) {
            addCriterion("MDT_YN >", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnGreaterThanOrEqualTo(String value) {
            addCriterion("MDT_YN >=", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnLessThan(String value) {
            addCriterion("MDT_YN <", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnLessThanOrEqualTo(String value) {
            addCriterion("MDT_YN <=", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnLike(String value) {
            addCriterion("MDT_YN like", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnNotLike(String value) {
            addCriterion("MDT_YN not like", value, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnIn(List<String> values) {
            addCriterion("MDT_YN in", values, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnNotIn(List<String> values) {
            addCriterion("MDT_YN not in", values, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnBetween(String value1, String value2) {
            addCriterion("MDT_YN between", value1, value2, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMdtYnNotBetween(String value1, String value2) {
            addCriterion("MDT_YN not between", value1, value2, "mdtYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnIsNull() {
            addCriterion("MULTI_YN is null");
            return (Criteria) this;
        }

        public Criteria andMultiYnIsNotNull() {
            addCriterion("MULTI_YN is not null");
            return (Criteria) this;
        }

        public Criteria andMultiYnEqualTo(String value) {
            addCriterion("MULTI_YN =", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnNotEqualTo(String value) {
            addCriterion("MULTI_YN <>", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnGreaterThan(String value) {
            addCriterion("MULTI_YN >", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnGreaterThanOrEqualTo(String value) {
            addCriterion("MULTI_YN >=", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnLessThan(String value) {
            addCriterion("MULTI_YN <", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnLessThanOrEqualTo(String value) {
            addCriterion("MULTI_YN <=", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnLike(String value) {
            addCriterion("MULTI_YN like", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnNotLike(String value) {
            addCriterion("MULTI_YN not like", value, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnIn(List<String> values) {
            addCriterion("MULTI_YN in", values, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnNotIn(List<String> values) {
            addCriterion("MULTI_YN not in", values, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnBetween(String value1, String value2) {
            addCriterion("MULTI_YN between", value1, value2, "multiYn");
            return (Criteria) this;
        }

        public Criteria andMultiYnNotBetween(String value1, String value2) {
            addCriterion("MULTI_YN not between", value1, value2, "multiYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnIsNull() {
            addCriterion("UPLOAD_YN is null");
            return (Criteria) this;
        }

        public Criteria andUploadYnIsNotNull() {
            addCriterion("UPLOAD_YN is not null");
            return (Criteria) this;
        }

        public Criteria andUploadYnEqualTo(String value) {
            addCriterion("UPLOAD_YN =", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnNotEqualTo(String value) {
            addCriterion("UPLOAD_YN <>", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnGreaterThan(String value) {
            addCriterion("UPLOAD_YN >", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnGreaterThanOrEqualTo(String value) {
            addCriterion("UPLOAD_YN >=", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnLessThan(String value) {
            addCriterion("UPLOAD_YN <", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnLessThanOrEqualTo(String value) {
            addCriterion("UPLOAD_YN <=", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnLike(String value) {
            addCriterion("UPLOAD_YN like", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnNotLike(String value) {
            addCriterion("UPLOAD_YN not like", value, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnIn(List<String> values) {
            addCriterion("UPLOAD_YN in", values, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnNotIn(List<String> values) {
            addCriterion("UPLOAD_YN not in", values, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnBetween(String value1, String value2) {
            addCriterion("UPLOAD_YN between", value1, value2, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andUploadYnNotBetween(String value1, String value2) {
            addCriterion("UPLOAD_YN not between", value1, value2, "uploadYn");
            return (Criteria) this;
        }

        public Criteria andSendCntIsNull() {
            addCriterion("SEND_CNT is null");
            return (Criteria) this;
        }

        public Criteria andSendCntIsNotNull() {
            addCriterion("SEND_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andSendCntEqualTo(Integer value) {
            addCriterion("SEND_CNT =", value, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntNotEqualTo(Integer value) {
            addCriterion("SEND_CNT <>", value, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntGreaterThan(Integer value) {
            addCriterion("SEND_CNT >", value, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEND_CNT >=", value, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntLessThan(Integer value) {
            addCriterion("SEND_CNT <", value, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntLessThanOrEqualTo(Integer value) {
            addCriterion("SEND_CNT <=", value, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntIn(List<Integer> values) {
            addCriterion("SEND_CNT in", values, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntNotIn(List<Integer> values) {
            addCriterion("SEND_CNT not in", values, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntBetween(Integer value1, Integer value2) {
            addCriterion("SEND_CNT between", value1, value2, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andSendCntNotBetween(Integer value1, Integer value2) {
            addCriterion("SEND_CNT not between", value1, value2, "sendCnt");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnIsNull() {
            addCriterion("ORGN_SEND_YN is null");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnIsNotNull() {
            addCriterion("ORGN_SEND_YN is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnEqualTo(String value) {
            addCriterion("ORGN_SEND_YN =", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnNotEqualTo(String value) {
            addCriterion("ORGN_SEND_YN <>", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnGreaterThan(String value) {
            addCriterion("ORGN_SEND_YN >", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnGreaterThanOrEqualTo(String value) {
            addCriterion("ORGN_SEND_YN >=", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnLessThan(String value) {
            addCriterion("ORGN_SEND_YN <", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnLessThanOrEqualTo(String value) {
            addCriterion("ORGN_SEND_YN <=", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnLike(String value) {
            addCriterion("ORGN_SEND_YN like", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnNotLike(String value) {
            addCriterion("ORGN_SEND_YN not like", value, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnIn(List<String> values) {
            addCriterion("ORGN_SEND_YN in", values, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnNotIn(List<String> values) {
            addCriterion("ORGN_SEND_YN not in", values, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnBetween(String value1, String value2) {
            addCriterion("ORGN_SEND_YN between", value1, value2, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgnSendYnNotBetween(String value1, String value2) {
            addCriterion("ORGN_SEND_YN not between", value1, value2, "orgnSendYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnIsNull() {
            addCriterion("TMPLT_YN is null");
            return (Criteria) this;
        }

        public Criteria andTmpltYnIsNotNull() {
            addCriterion("TMPLT_YN is not null");
            return (Criteria) this;
        }

        public Criteria andTmpltYnEqualTo(String value) {
            addCriterion("TMPLT_YN =", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnNotEqualTo(String value) {
            addCriterion("TMPLT_YN <>", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnGreaterThan(String value) {
            addCriterion("TMPLT_YN >", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnGreaterThanOrEqualTo(String value) {
            addCriterion("TMPLT_YN >=", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnLessThan(String value) {
            addCriterion("TMPLT_YN <", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnLessThanOrEqualTo(String value) {
            addCriterion("TMPLT_YN <=", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnLike(String value) {
            addCriterion("TMPLT_YN like", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnNotLike(String value) {
            addCriterion("TMPLT_YN not like", value, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnIn(List<String> values) {
            addCriterion("TMPLT_YN in", values, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnNotIn(List<String> values) {
            addCriterion("TMPLT_YN not in", values, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnBetween(String value1, String value2) {
            addCriterion("TMPLT_YN between", value1, value2, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andTmpltYnNotBetween(String value1, String value2) {
            addCriterion("TMPLT_YN not between", value1, value2, "tmpltYn");
            return (Criteria) this;
        }

        public Criteria andChkCndIsNull() {
            addCriterion("CHK_CND is null");
            return (Criteria) this;
        }

        public Criteria andChkCndIsNotNull() {
            addCriterion("CHK_CND is not null");
            return (Criteria) this;
        }

        public Criteria andChkCndEqualTo(String value) {
            addCriterion("CHK_CND =", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndNotEqualTo(String value) {
            addCriterion("CHK_CND <>", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndGreaterThan(String value) {
            addCriterion("CHK_CND >", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_CND >=", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndLessThan(String value) {
            addCriterion("CHK_CND <", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndLessThanOrEqualTo(String value) {
            addCriterion("CHK_CND <=", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndLike(String value) {
            addCriterion("CHK_CND like", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndNotLike(String value) {
            addCriterion("CHK_CND not like", value, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndIn(List<String> values) {
            addCriterion("CHK_CND in", values, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndNotIn(List<String> values) {
            addCriterion("CHK_CND not in", values, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndBetween(String value1, String value2) {
            addCriterion("CHK_CND between", value1, value2, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andChkCndNotBetween(String value1, String value2) {
            addCriterion("CHK_CND not between", value1, value2, "chkCnd");
            return (Criteria) this;
        }

        public Criteria andMsgNoIsNull() {
            addCriterion("MSG_NO is null");
            return (Criteria) this;
        }

        public Criteria andMsgNoIsNotNull() {
            addCriterion("MSG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMsgNoEqualTo(String value) {
            addCriterion("MSG_NO =", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoNotEqualTo(String value) {
            addCriterion("MSG_NO <>", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoGreaterThan(String value) {
            addCriterion("MSG_NO >", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoGreaterThanOrEqualTo(String value) {
            addCriterion("MSG_NO >=", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoLessThan(String value) {
            addCriterion("MSG_NO <", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoLessThanOrEqualTo(String value) {
            addCriterion("MSG_NO <=", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoLike(String value) {
            addCriterion("MSG_NO like", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoNotLike(String value) {
            addCriterion("MSG_NO not like", value, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoIn(List<String> values) {
            addCriterion("MSG_NO in", values, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoNotIn(List<String> values) {
            addCriterion("MSG_NO not in", values, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoBetween(String value1, String value2) {
            addCriterion("MSG_NO between", value1, value2, "msgNo");
            return (Criteria) this;
        }

        public Criteria andMsgNoNotBetween(String value1, String value2) {
            addCriterion("MSG_NO not between", value1, value2, "msgNo");
            return (Criteria) this;
        }

        public Criteria andCreIdIsNull() {
            addCriterion("CRE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreIdIsNotNull() {
            addCriterion("CRE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreIdEqualTo(String value) {
            addCriterion("CRE_ID =", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotEqualTo(String value) {
            addCriterion("CRE_ID <>", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdGreaterThan(String value) {
            addCriterion("CRE_ID >", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdGreaterThanOrEqualTo(String value) {
            addCriterion("CRE_ID >=", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdLessThan(String value) {
            addCriterion("CRE_ID <", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdLessThanOrEqualTo(String value) {
            addCriterion("CRE_ID <=", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdLike(String value) {
            addCriterion("CRE_ID like", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotLike(String value) {
            addCriterion("CRE_ID not like", value, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdIn(List<String> values) {
            addCriterion("CRE_ID in", values, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotIn(List<String> values) {
            addCriterion("CRE_ID not in", values, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdBetween(String value1, String value2) {
            addCriterion("CRE_ID between", value1, value2, "creId");
            return (Criteria) this;
        }

        public Criteria andCreIdNotBetween(String value1, String value2) {
            addCriterion("CRE_ID not between", value1, value2, "creId");
            return (Criteria) this;
        }

        public Criteria andCreDateIsNull() {
            addCriterion("CRE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreDateIsNotNull() {
            addCriterion("CRE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreDateEqualTo(Date value) {
            addCriterion("CRE_DATE =", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotEqualTo(Date value) {
            addCriterion("CRE_DATE <>", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateGreaterThan(Date value) {
            addCriterion("CRE_DATE >", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CRE_DATE >=", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateLessThan(Date value) {
            addCriterion("CRE_DATE <", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateLessThanOrEqualTo(Date value) {
            addCriterion("CRE_DATE <=", value, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateIn(List<Date> values) {
            addCriterion("CRE_DATE in", values, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotIn(List<Date> values) {
            addCriterion("CRE_DATE not in", values, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateBetween(Date value1, Date value2) {
            addCriterion("CRE_DATE between", value1, value2, "creDate");
            return (Criteria) this;
        }

        public Criteria andCreDateNotBetween(Date value1, Date value2) {
            addCriterion("CRE_DATE not between", value1, value2, "creDate");
            return (Criteria) this;
        }

        public Criteria andModIdIsNull() {
            addCriterion("MOD_ID is null");
            return (Criteria) this;
        }

        public Criteria andModIdIsNotNull() {
            addCriterion("MOD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModIdEqualTo(String value) {
            addCriterion("MOD_ID =", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotEqualTo(String value) {
            addCriterion("MOD_ID <>", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdGreaterThan(String value) {
            addCriterion("MOD_ID >", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdGreaterThanOrEqualTo(String value) {
            addCriterion("MOD_ID >=", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLessThan(String value) {
            addCriterion("MOD_ID <", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLessThanOrEqualTo(String value) {
            addCriterion("MOD_ID <=", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLike(String value) {
            addCriterion("MOD_ID like", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotLike(String value) {
            addCriterion("MOD_ID not like", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdIn(List<String> values) {
            addCriterion("MOD_ID in", values, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotIn(List<String> values) {
            addCriterion("MOD_ID not in", values, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdBetween(String value1, String value2) {
            addCriterion("MOD_ID between", value1, value2, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotBetween(String value1, String value2) {
            addCriterion("MOD_ID not between", value1, value2, "modId");
            return (Criteria) this;
        }

        public Criteria andModDateIsNull() {
            addCriterion("MOD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModDateIsNotNull() {
            addCriterion("MOD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModDateEqualTo(Date value) {
            addCriterion("MOD_DATE =", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateNotEqualTo(Date value) {
            addCriterion("MOD_DATE <>", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateGreaterThan(Date value) {
            addCriterion("MOD_DATE >", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_DATE >=", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateLessThan(Date value) {
            addCriterion("MOD_DATE <", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateLessThanOrEqualTo(Date value) {
            addCriterion("MOD_DATE <=", value, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateIn(List<Date> values) {
            addCriterion("MOD_DATE in", values, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateNotIn(List<Date> values) {
            addCriterion("MOD_DATE not in", values, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateBetween(Date value1, Date value2) {
            addCriterion("MOD_DATE between", value1, value2, "modDate");
            return (Criteria) this;
        }

        public Criteria andModDateNotBetween(Date value1, Date value2) {
            addCriterion("MOD_DATE not between", value1, value2, "modDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 28 17:23:17 KST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MDT_ADMS_CORS_MAJ
     *
     * @mbggenerated Wed Jan 28 17:23:17 KST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}