package com.apexsoft.ysprj.applicants.common.domain;

import java.util.Date;

public class DetailMajor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETL_MAJ.DETL_MAJ_CODE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    private String detlMajCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETL_MAJ.DETL_MAJ_NAME
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    private String detlMajName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETL_MAJ.USE_YN
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    private String useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETL_MAJ.CRE_ID
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    private String creId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETL_MAJ.CRE_DATE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETL_MAJ.MOD_ID
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    private String modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETL_MAJ.MOD_DATE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    private Date modDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETL_MAJ.DETL_MAJ_CODE
     *
     * @return the value of DETL_MAJ.DETL_MAJ_CODE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public String getDetlMajCode() {
        return detlMajCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETL_MAJ.DETL_MAJ_CODE
     *
     * @param detlMajCode the value for DETL_MAJ.DETL_MAJ_CODE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public void setDetlMajCode(String detlMajCode) {
        this.detlMajCode = detlMajCode == null ? null : detlMajCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETL_MAJ.DETL_MAJ_NAME
     *
     * @return the value of DETL_MAJ.DETL_MAJ_NAME
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public String getDetlMajName() {
        return detlMajName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETL_MAJ.DETL_MAJ_NAME
     *
     * @param detlMajName the value for DETL_MAJ.DETL_MAJ_NAME
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public void setDetlMajName(String detlMajName) {
        this.detlMajName = detlMajName == null ? null : detlMajName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETL_MAJ.USE_YN
     *
     * @return the value of DETL_MAJ.USE_YN
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETL_MAJ.USE_YN
     *
     * @param useYn the value for DETL_MAJ.USE_YN
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETL_MAJ.CRE_ID
     *
     * @return the value of DETL_MAJ.CRE_ID
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public String getCreId() {
        return creId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETL_MAJ.CRE_ID
     *
     * @param creId the value for DETL_MAJ.CRE_ID
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public void setCreId(String creId) {
        this.creId = creId == null ? null : creId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETL_MAJ.CRE_DATE
     *
     * @return the value of DETL_MAJ.CRE_DATE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETL_MAJ.CRE_DATE
     *
     * @param creDate the value for DETL_MAJ.CRE_DATE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETL_MAJ.MOD_ID
     *
     * @return the value of DETL_MAJ.MOD_ID
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public String getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETL_MAJ.MOD_ID
     *
     * @param modId the value for DETL_MAJ.MOD_ID
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public void setModId(String modId) {
        this.modId = modId == null ? null : modId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETL_MAJ.MOD_DATE
     *
     * @return the value of DETL_MAJ.MOD_DATE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public Date getModDate() {
        return modDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETL_MAJ.MOD_DATE
     *
     * @param modDate the value for DETL_MAJ.MOD_DATE
     *
     * @mbggenerated Mon Aug 25 20:25:07 KST 2014
     */
    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }
}